apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metaflow.fullname" . }}-app
  labels:
    {{- include "metaflow-app.labels" . | nindent 4 }}
spec:
  replicas: {{ tpl .Values.app.replicas . }}
  selector:
    matchLabels:
      {{- include "metaflow-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metaflow-app.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ tpl .Values.app.hostNetwork . }}
      dnsPolicy: {{ tpl .Values.app.dnsPolicy . }}
      imagePullSecrets:
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: metaflow-app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.app.repository . }}:{{ tpl .Values.image.app.tag . }}"
          imagePullPolicy: "{{ tpl .Values.image.app.pullPolicy . }}"
          ports:
            - name: app
              containerPort: 20404
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
          - name: app-config
            mountPath: /etc/metaflow/app.yaml
            subPath: app.yaml
          env:
          - name: K8S_NODE_IP_FOR_METAFLOW
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: TZ
            value: "{{ tpl .Values.timezone . }}"
      volumes:
        - name: app-config
          configMap:
            name: {{ include "metaflow.fullname" . }}
            items:
            - key: app.yaml
              path: app.yaml
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- include "appNodeaffinity" . | indent 6 }}
      {{- include "appPodAffinity" . | indent 6 }}
      {{- include "appPodAntiAffinity" . | indent 6 }}
      {{- if or .Values.global.tolerations .Values.tolerations }}
      tolerations:
      {{- if .Values.global.tolerations }}
      {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- end }}