kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "metaflow.fullname" . }}
  labels:
    {{- include "metaflow.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.config) $ | nindent 2 }}
