apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "metaflow.fullname" . }}-server
  labels:
    {{- include "metaflow.labels" . | nindent 4 }}
spec:
  replicas: {{ tpl .Values.replicas . }}
  podManagementPolicy: {{ tpl .Values.podManagementPolicy . }}
  serviceName: {{ include "metaflow.fullname" . }}-server-headless
  selector:
    matchLabels:
      {{- include "metaflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metaflow.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ tpl .Values.hostNetwork . }}
      dnsPolicy: {{ tpl .Values.dnsPolicy . }}
      imagePullSecrets:
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "metaflow.fullname" . }}-server
      containers:
        - name: metaflow-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.server.repository . }}:{{ tpl .Values.image.server.tag . }}"
          imagePullPolicy: "{{ tpl .Values.image.server.pullPolicy . }}"
          ports:
            - name: server
              containerPort: 20417
              protocol: TCP
            - containerPort: 20035
              name: grpc
              protocol: TCP
            - containerPort: 20135
              name: ssl-grpc
              protocol: TCP
            - containerPort: 20416
              name: querier
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: server
          readinessProbe:
            tcpSocket:
              port: server
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: server-config
            mountPath: /etc/server.yaml
            subPath: server.yaml
        - image: "{{ tpl .Values.image.elector.repository . }}:{{ tpl .Values.image.elector.tag . }}"
          imagePullPolicy: "{{ tpl .Values.image.elector.pullPolicy . }}"
          name: elector
          args:
          - --election=metaflow-server ## Service Name
          - --election-namespace={{- .Release.Namespace }}
          - --http=localhost:4040
          ports:
            - containerPort: 4040
          resources:
            requests:
              cpu: 100m
          env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
      volumes:
        - name: server-config
          configMap:
            name: {{ include "metaflow.fullname" . }}-server
            items:
            - key: server.yaml
              path: server.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
      {{- if or .Values.global.tolerations .Values.tolerations }}
      tolerations:
      {{- if .Values.global.tolerations }}
      {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}