runners:
  - name: "aws-amd64-32c"
    cloud: "aws"
    instance_type:
      - "c3.8xlarge"
      - "c5a.8xlarge"
      - "c5ad.8xlarge"
      - "c6a.8xlarge"
      - "c6i.8xlarge"
      - "c6id.8xlarge"
      - "cc2.8xlarge"

      - "c3.8xlarge"
      - "c5a.8xlarge"
      - "c5ad.8xlarge"
      - "c6a.8xlarge"
      - "c6i.8xlarge"
      - "c6id.8xlarge"
      - "cc2.8xlarge"

      - "c3.8xlarge"
      - "c5a.8xlarge"
      - "c5ad.8xlarge"
      - "c6a.8xlarge"
      - "c6i.8xlarge"
      - "c6id.8xlarge"
      - "cc2.8xlarge"

      - "c3.8xlarge"
      - "c5a.8xlarge"
      - "c5ad.8xlarge"
      - "c6a.8xlarge"
      - "c6i.8xlarge"
      - "c6id.8xlarge"
      - "cc2.8xlarge"
    machine_image: 
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"

      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"

      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"

      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
    region:
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"

      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"

      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"

      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
    preemptible: true
    labels:
      - "cirun-aws-amd64-32c"
  - name: "aws-arm64-32c"
    cloud: "aws"
    instance_type: 
      - "c6g.8xlarge"
      - "c6gd.8xlarge"
      - "c6gn.8xlarge"
      - "c7g.8xlarge"

      - "c6g.8xlarge"
      - "c6gd.8xlarge"
      - "c6gn.8xlarge"
      - "c7g.8xlarge"

      - "c6g.8xlarge"
      - "c6gd.8xlarge"
      - "c6gn.8xlarge"
      - "c7g.8xlarge"

      - "c6g.8xlarge"
      - "c6gd.8xlarge"
      - "c6gn.8xlarge"
      - "c7g.8xlarge"
    machine_image: 
      - "ami-05eebd9a9cda75f21"
      - "ami-05eebd9a9cda75f21"
      - "ami-05eebd9a9cda75f21"
      - "ami-05eebd9a9cda75f21"

      - "ami-0651b25cbd07dd480"
      - "ami-0651b25cbd07dd480"
      - "ami-0651b25cbd07dd480"
      - "ami-0651b25cbd07dd480"

      - "ami-00a6ebcf24bf95379"
      - "ami-00a6ebcf24bf95379"
      - "ami-00a6ebcf24bf95379"
      - "ami-00a6ebcf24bf95379"

      - "ami-0b615a940e613e870"
      - "ami-0b615a940e613e870"
      - "ami-0b615a940e613e870"
      - "ami-0b615a940e613e870"
    region:
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"

      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"

      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"

      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
    preemptible: true
    labels:
      - "cirun-aws-arm64-32c"
  - name: "aws-amd64-16c"
    cloud: "aws"
    instance_type:
      - "c4.4xlarge"
      - "c3.4xlarge"
      - "c6i.4xlarge"
      - "c5ad.4xlarge"
      - "c5.4xlarge"
      - "c5a.4xlarge"
      - "c5d.4xlarge"
      - "c6a.4xlarge"
      - "c6id.4xlarge"

      - "c4.4xlarge"
      - "c3.4xlarge"
      - "c6i.4xlarge"
      - "c5ad.4xlarge"
      - "c5.4xlarge"
      - "c5a.4xlarge"
      - "c5d.4xlarge"
      - "c6a.4xlarge"
      - "c6id.4xlarge"

      - "c4.4xlarge"
      - "c3.4xlarge"
      - "c6i.4xlarge"
      - "c5ad.4xlarge"
      - "c5.4xlarge"
      - "c5a.4xlarge"
      - "c5d.4xlarge"
      - "c6a.4xlarge"
      - "c6id.4xlarge"

      - "c4.4xlarge"
      - "c3.4xlarge"
      - "c6i.4xlarge"
      - "c5ad.4xlarge"
      - "c5.4xlarge"
      - "c5a.4xlarge"
      - "c5d.4xlarge"
      - "c6a.4xlarge"
      - "c6id.4xlarge"
    machine_image: 
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"
      - "ami-0b6d47878d0d5797b"

      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"
      - "ami-05e311eefc76f7e7a"

      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"
      - "ami-05d0f31079cacc1e8"

      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
      - "ami-0e5a8659475f55a69"
    region:
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"

      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"

      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"

      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
    preemptible: true
    labels:
      - "cirun-aws-amd64-16c"
