variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_IMAGE: docker-hosted.nexus.yunshan.net/rust-build:0.4
  NEXUS_REGISTRY: docker-hosted.nexus.yunshan.net
  DEPLOY_IMAGE: docker-hosted.nexus.yunshan.net/metaflow-agent

stages:
  - pre_build
  - verify
  - build_binary
  - package

verify-x64:
  stage: verify
  tags:
    - rust
  script:
    - cargo check
    - cargo fmt --all -- --check
    - cargo build --release
    - cargo build --release --bin metaflow-agent-ctl
    - cargo test
    # - cargo clean
  # artifacts:
  #     paths:
  #       - target/*
  except:
    - /B_LC_RELEASE_.*/
    - master

rust-build-env:
  stage: pre_build
  tags:
    - docker
  before_script:
    - docker login -u admin -p yunshan3302 $NEXUS_REGISTRY
  script:
    - cd docker
    - docker build --pull -t $BUILD_IMAGE -f Dockerfile.build .
    - docker push $BUILD_IMAGE
    - echo "Pushed $BUILD_IMAGE"
    - docker image rm $BUILD_IMAGE
  only:
    - package-rust


binary-x64:
  stage: build_binary
  tags:
    - rust
  script:
    - cargo build --release
    - cargo build --release --bin metaflow-agent-ctl
    - ls -alh target/release
    # - cargo clean
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/
  artifacts:
      paths:
        - target/release/metaflow-agent
        - target/release/metaflow-agent-ctl
        - src/ebpf/data/*
        - src/ebpf/kernel/socket_trace.elf
        - src/ebpf/libebpf.a
        - src/ebpf/metaflow-ebpfctl
        - src/proto/*
rpm-x64:
  stage: package
  tags:
    - rust
  script:
    - rpmbuild -bb metaflow-agent.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
    - rpmbuild -bb metaflow-agent_docker.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
    - zip -r -q artifacts.zip x86_64/
    - curl -v --user 'admin:yunshan3302' --upload-file artifacts.zip http://nexus.yunshan.net/repository/platform/trident-rs/$CI_COMMIT_REF_NAME/x86_64/artifacts.zip
    - REV=$(git rev-list --count HEAD)
    - curl -v --user 'admin:yunshan3302' --upload-file artifacts.zip http://nexus.yunshan.net/repository/platform/trident-rs/$CI_COMMIT_REF_NAME/x86_64/artifacts_${REV}.zip
    # - cargo clean
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/
  artifacts:
      paths:
        - x86_64/metaflow*.rpm

docker-x64:
  stage: package
  tags:
    - rust
  script:
    - cp target/release/metaflow-agent docker/
    - cp target/release/metaflow-agent-ctl docker/
    - cp src/ebpf/metaflow-ebpfctl docker/
    - cp -r src/ebpf/data docker/
    - cd docker
    - ls
    - RELEASE=$(echo ${CI_COMMIT_REF_NAME//B_LC_RELEASE_} | tr '_' '.' | sed 's/master/latest/')
    - REV=$(git rev-list --count HEAD)
    # e.g. metaflow-agnet:latest
    - docker build --pull -t  $DEPLOY_IMAGE:$RELEASE .
    - docker push $DEPLOY_IMAGE:$RELEASE
    # e.g. metaflow-agnet:latest.50
    - docker build --pull -t  $DEPLOY_IMAGE:$RELEASE.$REV .
    - docker push $DEPLOY_IMAGE:$RELEASE.$REV
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/
  # artifacts:
  #     paths:
  #       - x86_64/metaflow*.rpm


# 部分docker环境没有安装cargo命令，这里先注释掉，后续可参考
# package-docker:
#  stage: package
#  tags:
#    - docker
#  before_script:
#    - docker login -u admin -p yunshan3302 $NEXUS_REGISTRY
#  script:
#    - cargo build --release
#    - cargo build --release --bin metaflow-agent-ctl
#    - cp target/release/metaflow-agent docker/
#    - cp target/release/metaflow-agent-ctl docker/
#    - cp src/ebpf/metaflow-ebpfctl docker/
#    - cp -r src/ebpf/data docker/
#    - cd docker
#    - ls
#    - RELEASE=$(echo ${CI_COMMIT_REF_NAME//B_LC_RELEASE_} | tr '_' '.' | sed 's/master/latest/')
#    - REV=$(git rev-list --count HEAD)
#    # e.g. metaflow-agnet:latest
#    - docker build --pull -t  $DEPLOY_IMAGE:$RELEASE .
#    - docker push $DEPLOY_IMAGE:$RELEASE
#    # e.g. metaflow-agnet:latest.50
#    - docker build --pull -t  $DEPLOY_IMAGE:$RELEASE.$REV .
#    - docker push $DEPLOY_IMAGE:$RELEASE.$REV
#  only:
#    - master
#    - /B_LC_RELEASE_.*/
#    - /feature-.*/
