stages:
  - verify

verify:
  stage: verify
  script:
    - make clean
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make test
  only:
    - pushes
