variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - verify
  - package

verify-x64:
  stage: verify
  tags:
    - x64

  script:
    - cargo build
    - cargo build --bin trident-ctl
    - cargo test
    - cargo fmt --all -- --check

package-x64:
  stage: package
  tags:
    - x64

  script:
    - cargo build --release
    - cargo build --release --bin trident-ctl
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/
