variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_IMAGE: docker-hosted.nexus.yunshan.net/rust-build:0.4
  NEXUS_REGISTRY: docker-hosted.nexus.yunshan.net
  DEPLOY_IMAGE: docker-hosted.nexus.yunshan.net/metaflow-agent
stages:
  - pre_build
  # - verify
  - build-binary
  - build-docker-image



create_build_image:
  stage: pre_build
  tags:
    - docker
  before_script:
    - docker login -u admin -p yunshan3302 $NEXUS_REGISTRY
  script:
    - cd docker
    - docker build --pull -t $BUILD_IMAGE -f Dockerfile.build .
    - docker push $BUILD_IMAGE
    - echo "Pushed $BUILD_IMAGE"
    - docker image rm $BUILD_IMAGE
  only:
    - yifeng

# verify-x64:
#   stage: verify
#   tags:
#     # - kubernetes
#     - x64
#   # image: $BUILD_IMAGE
#   script:
#     - cargo build -j 1
#     - cargo build -j 1 --bin metaflow-agent-ctl
#     - cargo test
#     - cargo fmt --all -- --check
#     - cargo clean

binary-x64:
  stage: build-binary
  tags:
    # - kubernetes
    - x64
  # image: $BUILD_IMAGE
  script:
    - cargo build --release
    - cargo build --release --bin metaflow-agent-ctl
    - ls
    - cp target/release/metaflow-agent .
    - cp target/release/metaflow-agent-ctl .
    - cp src/ebpf/metaflow-ebpfctl .
    - ls
    - cargo clean
  artifacts:
      paths:
        - metaflow-agent
        - metaflow-agent-ctl
        - metaflow-ebpfctl
        - src/ebpf/data

build_image:
  stage: build-docker-image
  tags:
    - docker
  before_script:
    - docker login -u admin -p yunshan3302 $NEXUS_REGISTRY
  script:
    - cp metaflow-agent docker/
    - cp metaflow-agent-ctl docker/
    - cp metaflow-ebpfctl docker/
    - cp -r src/ebpf/data docker/
    - cd docker
    - ls
    - RELEASE=$(echo ${CI_COMMIT_REF_NAME//B_LC_RELEASE_} | tr '_' '.' | sed 's/master/latest/')
    - REV=$(git rev-list --count HEAD)
    # e.g. metaflow-agnet:latest
    - docker build --pull -t  $DEPLOY_IMAGE:$RELEASE .
    - docker push $DEPLOY_IMAGE:$RELEASE
    # e.g. metaflow-agnet:latest.50
    - docker build --pull -t  $DEPLOY_IMAGE:$RELEASE.$REV .
    - docker push $DEPLOY_IMAGE:$RELEASE.$REV
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/