stages:
  - verify

verify:
  stage: verify
  tags:
    - x64
  script:
    - make clean
    - go mod tidy && go mod download
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make test
