

apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-server
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
{{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  ports:
  {{- $serviceType := .Values.service.type -}}
  {{- range $index, $item := $.Values.service.ports }}
  - name: {{ $item.name }}
    port: {{ $item.port }}
    targetPort: {{ $item.targetPort }}
    {{- if eq $serviceType "NodePort" }}
    nodePort: {{ $item.nodePort | default "" }}
    {{- end }}
    protocol: {{ $item.protocol }}
    {{- end }}
{{- if .Values.service.additionalPorts }}
{{ toYaml .Values.service.additionalPorts | indent 2 }}
{{- end }}
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
  type: "{{ .Values.service.type }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-headless
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
  type: ClusterIP