# Value         , DisplayName   , Description
create          , 创建/同步     , 
delete          , 删除          ,
update-state    , 状态改变      ,
migrate         , 迁移          ,
recreate        , 重建          ,
add-ip          , 增加IP        ,
remove-ip       , 删除IP        ,
modify          , 修改定义       ,
attach-config   , 关联配置       ,
modify-config   , 修改配置       ,
detach-config   , 清除配置       ,
