# Value , DisplayName     , Description
1       , 云服务器        ,
5       , 路由器          ,
6       , 宿主机          ,
9       , DHCP网关        ,
10      , 容器POD         ,
11      , 容器服务        ,
12      , Redis           ,
13      , RDS             ,
14      , 容器节点        ,
15      , 负载均衡器      ,
16      , NAT网关         ,
120     , 进程            ,
