# Value , DisplayName     , Description
0       , Internet IP     ,
1       , 云服务器        ,
5       , 路由器          ,
6       , 宿主机          ,
9       , DHCP 网关       ,
10      , 容器 POD        ,
11      , 容器服务        ,
12      , RDS             ,
13      , Redis           ,
14      , 容器节点        ,
15      , 负载均衡器      ,
16      , NAT 网关        ,
120     , 进程            ,
255     , IP              ,
