/**
 * Copyright (c) 2025 Yunshan Networks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by go run field_gen.go. DO NOT EDIT.

package pcap_verify

var ResponseFieldToAppProtoLogsDataFieldPath = map[string]string{
	"response_status":    "resp.status",
	"start_time":         "base.start_time",
	"end_time":           "base.end_time",
	"ip_0":               "base.ip_src",
	"ip_1":               "base.ip_dst",
	"server_port":        "base.port_dst",
	"endpoint":           "req.endpoint",
	"l7_protocol":        "base.head.proto",
	"biz_protocol":       "ext_info.protocol_str",
	"biz_type":           "base.biz_type",
	"request_type":       "req.req_type",
	"request_domain":     "req.domain",
	"request_resource":   "req.resource",
	"response_code":      "resp.code",
	"response_exception": "resp.exception",
	"response_result":    "resp.result",
	"request_id":         "ext_info.request_id",
	"x_request_id_0":     "ext_info.x_request_id_0",
	"x_request_id_1":     "ext_info.x_request_id_1",
	"http_proxy_client":  "ext_info.client_ip",
	"trace_id":           "trace_info.trace_id",
	"span_id":            "trace_info.span_id",
	"version":            "version",
	"biz_code":           "biz_code",
	"biz_scenario":       "biz_scenario",
	"biz_response_code":  "biz_response_code",
}

type PartialConvertedAppProtoLogsData struct {
	ResponseStatus    uint32 `json:"response_status,omitempty"`
	StartTime         string `json:"start_time,omitempty"`
	EndTime           string `json:"end_time,omitempty"`
	Ip0               string `json:"ip_0,omitempty"`
	Ip1               string `json:"ip_1,omitempty"`
	ServerPort        uint32 `json:"server_port,omitempty"`
	Endpoint          string `json:"endpoint,omitempty"`
	L7Protocol        uint32 `json:"l7_protocol,omitempty"`
	BizProtocol       string `json:"biz_protocol,omitempty"`
	BizType           uint32 `json:"biz_type,omitempty"`
	RequestType       string `json:"request_type,omitempty"`
	RequestDomain     string `json:"request_domain,omitempty"`
	RequestResource   string `json:"request_resource,omitempty"`
	ResponseCode      int32  `json:"response_code,omitempty"`
	ResponseException string `json:"response_exception,omitempty"`
	ResponseResult    string `json:"response_result,omitempty"`
	RequestId         uint32 `json:"request_id,omitempty"`
	XRequestId0       string `json:"x_request_id_0,omitempty"`
	XRequestId1       string `json:"x_request_id_1,omitempty"`
	HttpProxyClient   string `json:"http_proxy_client,omitempty"`
	TraceId           string `json:"trace_id,omitempty"`
	SpanId            string `json:"span_id,omitempty"`
	Version           string `json:"version,omitempty"`
	BizCode           string `json:"biz_code,omitempty"`
	BizScenario       string `json:"biz_scenario,omitempty"`
	BizResponseCode   string `json:"biz_response_code,omitempty"`
}
