## Note: the only difference with linux is log-file
#
## controller ip
controller-ips:
  - 127.0.0.1

## controller listen port
#controller-port: 30035
## controller security authenticate port
#controller-tls-port: 30135

## controller certificate file prefix, contain path
## if certificate file exists, do certificate; or no
## certificate file naming rule is prefix.controller-ip
## example
## controller-cert-file-prefix is /etc/deepflow-server.cert
## controller ip is: 10.10.10.10
## so certificate file name is deepflow-server.cert.10.10.10.10 in /etc/
#controller-cert-file-prefix: ""

## logfile path
#log-file: "C:\\DeepFlow\\deepflow-agent\\log\\deepflow-agent.log"

## When running in the K8s environment, if this value is empty, 
## deepflow-agent requests deepflow-server through the MD5 of the CA file of the K8s cluster to get k8s-cluster-id. 
## You can also manually fill in an existing k8s-cluster-id in deepflow-server.
#kubernetes-cluster-id:

## When running in the K8s environment, if this is configured, deepflow-agent will carry this name when
## requesting to get k8s-cluster-id, and deepflow-server will use this name to mark the K8s cluster.
#kubernetes-cluster-name:

## 支持采集器自动加入组
#vtap-group-id-request: ""

## If specified, use this name for hostname
#override-os-hostname:

## Number of worker threads of tokio, range [1, 32768), defaults to 16
#tokio-worker-thread-number: 16
