apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
{{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  ports:
  {{- $serviceType := .Values.service.type -}}
  {{- range .Values.service.ports }}
  - name: {{ tpl .name $ }}
    port: {{ tpl (toString .port) $ }}
    targetPort: {{ tpl (toString .targetPort) $ }}
    {{- if and (eq $serviceType "NodePort") (.nodePort) }}
    nodePort: {{ tpl (toString .nodePort) $ }}
    {{- end }}
    protocol: {{ tpl .protocol $ }}
    {{- end }}
{{- if .Values.service.additionalPorts }}
{{ toYaml .Values.service.additionalPorts | indent 2 }}
{{- end }}
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
  type: "{{ .Values.service.type }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-headless
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
  type: ClusterIP

{{- $replicas := int (tpl .Values.replicas . |toString) }}
{{- range $i := until $replicas }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" $ }}-headless-{{ $i }}
  labels:
    {{- include "clickhouse.labels" $ | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    {{- include "clickhouse.selectorLabels" $ | nindent 4 }}
    "statefulset.kubernetes.io/pod-name": {{ include "clickhouse.fullname" $ }}-{{ $i }}
{{- end }}
