[package]
name = "rust_sample"
version = "0.1.0"
authors = ["Yin Jiping <jiping@yunshan.net>"]
edition = "2021"
build = "build.rs"

[build-dependencies]
dunce = "0.1.1"

[dependencies]
libc = "0.2"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
