FROM docker.io/alpine

ARG TZ='Asia/Harbin'
ENV DEFAULT_TZ ${TZ}
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk upgrade --update \
    && apk add -U tzdata \
    && cp /usr/share/zoneinfo/${DEFAULT_TZ} /etc/localtime \
    && apk del tzdata \
    && rm -rf /var/cache/apk/*

# 修改root密码为root
RUN chmod 600 /etc/passwd; \
    echo "root:root" | chpasswd; \
    chmod 000 /etc/passwd

RUN mkdir -p /lib64 /usr/share/metaflow-agent
COPY require /lib64
COPY metaflow-ebpfctl /bin/
COPY data /usr/share/metaflow-agent

# 普通用户获取su命令权限
RUN chmod 4755 /bin/busybox
