apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metaflow-agent
  namespace: yunshan-metaflow
spec:
  selector:
    matchLabels:
      app: metaflow-agent
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/metaflow-agent: unconfined
      name: metaflow-agent
      namespace: yunshan-metaflow
      labels:
        app: metaflow-agent
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: metaflow-agent
          image: metaflow-agent:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
      volumes:
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
