// Code generated by "stringer -type=DomainType -trimprefix=DOMAIN_TYPE_ -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DOMAIN_TYPE_UNKNOWN - -1]
	_ = x[DOMAIN_TYPE_OPENSTACK-1]
	_ = x[DOMAIN_TYPE_VSPHERE-2]
	_ = x[DOMAIN_TYPE_TENCENT-4]
	_ = x[DOMAIN_TYPE_FILEREADER-5]
	_ = x[DOMAIN_TYPE_AWS-6]
	_ = x[DOMAIN_TYPE_ALIYUN-9]
	_ = x[DOMAIN_TYPE_HUAWEI_PRIVATE-10]
	_ = x[DOMAIN_TYPE_KUBERNETES-11]
	_ = x[DOMAIN_TYPE_SIMULATION-12]
	_ = x[DOMAIN_TYPE_HUAWEI-13]
	_ = x[DOMAIN_TYPE_QINGCLOUD-14]
	_ = x[DOMAIN_TYPE_QINGCLOUD_PRIVATE-15]
	_ = x[DOMAIN_TYPE_AZURE-18]
	_ = x[DOMAIN_TYPE_APSARA_STACK-19]
	_ = x[DOMAIN_TYPE_TENCENT_TCE-20]
	_ = x[DOMAIN_TYPE_AGENT_SYNC-23]
	_ = x[DOMAIN_TYPE_MICROSOFT_ACS-24]
	_ = x[DOMAIN_TYPE_BAIDU_BCE-25]
	_ = x[DOMAIN_TYPE_ESHORE-26]
	_ = x[DOMAIN_TYPE_CLOUD_TOWER-27]
	_ = x[DOMAIN_TYPE_NFVO-28]
	_ = x[DOMAIN_TYPE_SUGON-29]
	_ = x[DOMAIN_TYPE_VOLCENGINE-30]
	_ = x[DOMAIN_TYPE_H3C-31]
}

const (
	_DomainType_name_0 = "UNKNOWN"
	_DomainType_name_1 = "openstackvsphere"
	_DomainType_name_2 = "tencentfilereaderaws"
	_DomainType_name_3 = "aliyunhuawei_privatekubernetessimulationhuaweiqingcloudqingcloud_private"
	_DomainType_name_4 = "azureapsara_stacktencent_tce"
	_DomainType_name_5 = "agent_syncmicrosoft_acsbaidu_bceeshorecloudtowernfvosugonvolcengineh3c"
)

var (
	_DomainType_index_1 = [...]uint8{0, 9, 16}
	_DomainType_index_2 = [...]uint8{0, 7, 17, 20}
	_DomainType_index_3 = [...]uint8{0, 6, 20, 30, 40, 46, 55, 72}
	_DomainType_index_4 = [...]uint8{0, 5, 17, 28}
	_DomainType_index_5 = [...]uint8{0, 10, 23, 32, 38, 48, 52, 57, 67, 70}
)

func (i DomainType) String() string {
	switch {
	case i == -1:
		return _DomainType_name_0
	case 1 <= i && i <= 2:
		i -= 1
		return _DomainType_name_1[_DomainType_index_1[i]:_DomainType_index_1[i+1]]
	case 4 <= i && i <= 6:
		i -= 4
		return _DomainType_name_2[_DomainType_index_2[i]:_DomainType_index_2[i+1]]
	case 9 <= i && i <= 15:
		i -= 9
		return _DomainType_name_3[_DomainType_index_3[i]:_DomainType_index_3[i+1]]
	case 18 <= i && i <= 20:
		i -= 18
		return _DomainType_name_4[_DomainType_index_4[i]:_DomainType_index_4[i+1]]
	case 23 <= i && i <= 31:
		i -= 23
		return _DomainType_name_5[_DomainType_index_5[i]:_DomainType_index_5[i+1]]
	default:
		return "DomainType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
