// Code generated by "stringer -type=DomainEnabled -trimprefix=DOMAIN_ENABLED_ -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DOMAIN_ENABLED_DISABLE-0]
	_ = x[DOMAIN_ENABLED_ENABLE-1]
}

const _DomainEnabled_name = "DISABLEENABLE"

var _DomainEnabled_index = [...]uint8{0, 7, 13}

func (i DomainEnabled) String() string {
	if i < 0 || i >= DomainEnabled(len(_DomainEnabled_index)-1) {
		return "DomainEnabled(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DomainEnabled_name[_DomainEnabled_index[i]:_DomainEnabled_index[i+1]]
}
