// Code generated by "stringer -type=DomainState -trimprefix=DOMAIN_STATE_ -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DOMAIN_STATE_NORMAL-1]
	_ = x[DOMAIN_STATE_EXCEPTION-3]
	_ = x[DOMAIN_STATE_WARN-4]
}

const (
	_DomainState_name_0 = "NORMAL"
	_DomainState_name_1 = "EXCEPTIONWARN"
)

var (
	_DomainState_index_1 = [...]uint8{0, 9, 13}
)

func (i DomainState) String() string {
	switch {
	case i == 1:
		return _DomainState_name_0
	case 3 <= i && i <= 4:
		i -= 3
		return _DomainState_name_1[_DomainState_index_1[i]:_DomainState_index_1[i+1]]
	default:
		return "DomainState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
