// Code generated by "stringer -type=PluginType -trimprefix=PLUGIN_TYPE_ -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLUGIN_TYPE_WASM-1]
	_ = x[PLUGIN_TYPE_SO-2]
	_ = x[PLUGIN_TYPE_LUA-3]
}

const _PluginType_name = "WASMSOLUA"

var _PluginType_index = [...]uint8{0, 4, 6, 9}

func (i PluginType) String() string {
	i -= 1
	if i < 0 || i >= PluginType(len(_PluginType_index)-1) {
		return "PluginType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PluginType_name[_PluginType_index[i]:_PluginType_index[i+1]]
}
