// Code generated by "stringer -type=PluginUser -trimprefix=PLUGIN_USER_ -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLUGIN_USER_AGENT-1]
	_ = x[PLUGIN_USER_SERVER-2]
}

const _PluginUser_name = "AGENTSERVER"

var _PluginUser_index = [...]uint8{0, 5, 11}

func (i PluginUser) String() string {
	i -= 1
	if i < 0 || i >= PluginUser(len(_PluginUser_index)-1) {
		return "PluginUser(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PluginUser_name[_PluginUser_index[i]:_PluginUser_index[i+1]]
}
