// Code generated by "stringer -type=VtapTapMode -trimprefix=VTAP_TAP_MODE_ -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VTAP_TAP_MODE_LOCAL-0]
	_ = x[VTAP_TAP_MODE_MIRROR-1]
	_ = x[VTAP_TAP_MODE_DEDICATED-2]
}

const _VtapTapMode_name = "localmirrordedicated"

var _VtapTapMode_index = [...]uint8{0, 5, 11, 20}

func (i VtapTapMode) String() string {
	if i < 0 || i >= VtapTapMode(len(_VtapTapMode_index)-1) {
		return "VtapTapMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VtapTapMode_name[_VtapTapMode_index[i]:_VtapTapMode_index[i+1]]
}
