// Code generated by "stringer -type=VtapException -trimprefix=VTAP_EXCEPTION_ -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VTAP_EXCEPTION_LICENSE_NOT_ENGOUTH-268435456]
	_ = x[VTAP_EXCEPTION_ALLOC_ANALYZER_FAILED-1073741824]
	_ = x[VTAP_EXCEPTION_ALLOC_CONTROLLER_FAILED-2147483648]
}

const (
	_VtapException_name_0 = "LICENSE_NOT_ENGOUTH"
	_VtapException_name_1 = "ALLOC_ANALYZER_FAILED"
	_VtapException_name_2 = "ALLOC_CONTROLLER_FAILED"
)

func (i VtapException) String() string {
	switch {
	case i == 268435456:
		return _VtapException_name_0
	case i == 1073741824:
		return _VtapException_name_1
	case i == 2147483648:
		return _VtapException_name_2
	default:
		return "VtapException(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
