// Code generated by "stringer -type=VtapState -trimprefix=VTAP_STATE_ -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VTAP_STATE_NOT_CONNECTED-0]
	_ = x[VTAP_STATE_NORMAL-1]
	_ = x[VTAP_STATE_DISABLE-2]
	_ = x[VTAP_STATE_PENDING-3]
}

const _VtapState_name = "LOSTNORMALDISABLEPENDING"

var _VtapState_index = [...]uint8{0, 4, 10, 17, 24}

func (i VtapState) String() string {
	if i < 0 || i >= VtapState(len(_VtapState_index)-1) {
		return "VtapState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VtapState_name[_VtapState_index[i]:_VtapState_index[i+1]]
}
