// Code generated by "stringer -type=VtapType -trimprefix=VTAP_TYPE_ -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VTAP_TYPE_KVM-1]
	_ = x[VTAP_TYPE_ESXI-2]
	_ = x[VTAP_TYPE_WORKLOAD_V-3]
	_ = x[VTAP_TYPE_WORKLOAD_P-5]
	_ = x[VTAP_TYPE_DEDICATED-6]
	_ = x[VTAP_TYPE_POD_HOST-7]
	_ = x[VTAP_TYPE_POD_VM-8]
	_ = x[VTAP_TYPE_TUNNEL_DECAPSULATION-9]
	_ = x[VTAP_TYPE_HYPER_V-10]
	_ = x[VTAP_TYPE_K8S_SIDECAR-12]
}

const (
	_VtapType_name_0 = "KVMESXICHOST_VM"
	_VtapType_name_1 = "CHOST_BMDEDICATEDK8S_BMK8S_VMTUN_DECAPHYPER_V"
	_VtapType_name_2 = "K8S_SIDECAR"
)

var (
	_VtapType_index_0 = [...]uint8{0, 3, 7, 15}
	_VtapType_index_1 = [...]uint8{0, 8, 17, 23, 29, 38, 45}
)

func (i VtapType) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _VtapType_name_0[_VtapType_index_0[i]:_VtapType_index_0[i+1]]
	case 5 <= i && i <= 10:
		i -= 5
		return _VtapType_name_1[_VtapType_index_1[i]:_VtapType_index_1[i+1]]
	case i == 12:
		return _VtapType_name_2
	default:
		return "VtapType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
