{{- if  .Values.externalMySQL.enabled  }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
subsets:
 - addresses:
     - ip: {{ .Values.externalMySQL.hostIP }}
   ports:
     - name: mysql
       port: {{ .Values.externalMySQL.port }}
       protocol: TCP
{{- end }}