# Default values for deepflow-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  podAntiAffinityLabelSelector: []
  podAntiAffinityTermLabelSelector: []
  podAffinityLabelSelector: []
  podAffinityTermLabelSelector: []
  nodeAffinityLabelSelector: []
  nodeAffinityTermLabelSelector: []


image:
  repository: deepflowce/deepflow-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
agentFullnameOverride: "deepflow-agent"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000
hostNetwork: "true"
securityContext: 
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  
nodeIPInjection: false

service:
  ## Configuration for Clickhouse service
  ##
  annotations: {}
  labels: {}
  clusterIP: ""

  ## Port for Clickhouse Service to listen on
  ##

  ports:
  - name: receive
    port: 80
    targetPort: receive
    nodePort: 
    protocol: TCP

  ## Additional ports to open for server service
  additionalPorts: []

  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  ## Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints
  ## must be Local
  externalTrafficPolicy: Local

  ## Service type
  ##
  type: ClusterIP

deepflowServerNodeIPS:
- deepflow-server
deepflowK8sClusterID: 
agentGroupID:
## This command takes effect when agent-group-config external_agent_http_proxy_enabled=1 is configured using deepflow-ctl
## Set the port to the agent-group-config port
externalAgentHttpProxyPort: 38086

deepflowAgentConfig: 
  deepflow-agent.yaml: |
    controller-ips:
    {{- tpl (toYaml $.Values.deepflowServerNodeIPS ) .| nindent 4 }}
    {{ if .Values.agentGroupID }}vtap-group-id-request: {{ .Values.agentGroupID }}{{ end }}
    {{ if .Values.deepflowK8sClusterID }}kubernetes-cluster-id: {{ .Values.deepflowK8sClusterID }}{{ end }}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

podAntiAffinityLabelSelector: []
podAntiAffinityTermLabelSelector: []
podAffinityLabelSelector: []
podAffinityTermLabelSelector: []
nodeAffinityLabelSelector: []
nodeAffinityTermLabelSelector: []

