package description

var ResourceTags = []*TagDescription{
	NewTagDescription("region", "region_0", "region_1", "区域", RESOURCE_ID),
	NewTagDescription("region_name", "region_name_0", "region_name_1", "区域名称", RESOURCE_NAME),
	NewTagDescription("az", "az_0", "az_1", "可用区", RESOURCE_ID),
	NewTagDescription("az_name", "az_name_0", "az_name_1", "可用区名称", RESOURCE_NAME),
	NewTagDescription("host", "host_0", "host_1", "宿主机", RESOURCE_ID),
	NewTagDescription("host_name", "host_name_0", "host_name_1", "宿主机名称", RESOURCE_NAME),
	NewTagDescription("vm", "vm_0", "vm_1", "云服务器", RESOURCE_ID),
	NewTagDescription("vm_name", "vm_name_0", "vm_name_1", "云服务器名称", RESOURCE_NAME),
	NewTagDescription("router", "router_0", "router_1", "路由器", RESOURCE_ID),
	NewTagDescription("router_name", "router_name_0", "router_name_1", "路由器名称", RESOURCE_NAME),
	NewTagDescription("dhcp_port", "dhcp_port_0", "dhcp_port_1", "DHCP网关", RESOURCE_ID),
	NewTagDescription("dhcp_port_name", "dhcp_port_name_0", "dhcp_port_name_1", "DHCP网关名称", RESOURCE_NAME),
	NewTagDescription("pod_service", "pod_service_0", "pod_service_1", "容器服务", RESOURCE_ID),
	NewTagDescription("pod_service_name", "pod_service_name_0", "pod_service_name_1", "容器服务名称", RESOURCE_NAME),
	NewTagDescription("redis", "redis_0", "redis_1", "Redis", RESOURCE_ID),
	NewTagDescription("redis_name", "redis_name_0", "redis_name_1", "Redis名称", RESOURCE_NAME),
	NewTagDescription("rds", "rds_0", "rds_1", "RDS", RESOURCE_ID),
	NewTagDescription("rds_name", "rds_name_0", "rds_name_1", "RDS名称", RESOURCE_NAME),
	NewTagDescription("lb", "lb_0", "lb_1", "负载均衡器", RESOURCE_ID),
	NewTagDescription("lb_name", "lb_name_0", "lb_name_1", "负载均衡器名称", RESOURCE_NAME),
	NewTagDescription("nat_gateway", "nat_gateway_0", "nat_gateway_1", "NAT网关", RESOURCE_ID),
	NewTagDescription("nat_gateway_name", "nat_gateway_name_0", "nat_gateway_name_1", "NAT网关名称", RESOURCE_NAME),
	NewTagDescription("pod_node", "pod_node_0", "pod_node_1", "容器节点", RESOURCE_ID),
	NewTagDescription("pod_node_name", "pod_node_name_0", "pod_node_name_1", "容器节点名称", RESOURCE_NAME),
	NewTagDescription("pod_ns", "pod_ns_0", "pod_ns_1", "命名空间", RESOURCE_ID),
	NewTagDescription("pod_ns_name", "pod_ns_name_0", "pod_ns_name_1", "命名空间名称", RESOURCE_NAME),
	NewTagDescription("pod_group", "pod_group_0", "pod_group_1", "工作负载", RESOURCE_ID),
	NewTagDescription("pod_group_name", "pod_group_name_0", "pod_group_name_1", "工作负载名称", RESOURCE_NAME),
	NewTagDescription("pod", "pod_0", "pod_1", "容器POD", RESOURCE_ID),
	NewTagDescription("pod_name", "pod_name_0", "pod_name_1", "容器POD名称", RESOURCE_NAME),
	NewTagDescription("pod_cluster", "pod_cluster_0", "pod_cluster_1", "容器集群", RESOURCE_ID),
	NewTagDescription("pod_cluster_name", "pod_cluster_name_0", "pod_cluster_name_1", "容器集群名称", RESOURCE_NAME),
	NewTagDescription("l3_epc", "l3_epc_0", "l3_epc_1", "VPC", RESOURCE_ID),
	NewTagDescription("l3_epc_name", "l3_epc_name_0", "l3_epc_name_1", "VPC名称", RESOURCE_NAME),
	NewTagDescription("subnet", "subnet_0", "subnet_1", "子网", RESOURCE_ID),
	NewTagDescription("subnet_name", "subnet_name_0", "subnet_name_1", "子网名称", RESOURCE_NAME),
	NewTagDescription("ip", "ip_0", "ip_1", "IP", "ip"),

	NewTagDescription("tap_type", "tap_type", "tap_type", "采集点", RESOURCE_ID),
	NewTagDescription("tap_type_name", "tap_type_name", "tap_type_name", "采集点名称", RESOURCE_NAME),
	NewTagDescription("vtap", "vtap", "vtap", "采集器", RESOURCE_ID),
	NewTagDescription("vtap_name", "vtap_name", "vtap_name", "采集器名称", RESOURCE_NAME),
}
