name: config_map
orm_name: ConfigMap

cache_diffbase:
  enabled: true
  fields:
    - name: name
      orm_name: Name
      type: string
    - name: data
      orm_name: Data
      type: string
      from: bytes
      is_large: true
    - name: data_hash
      orm_name: DataHash
      type: string

cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    orm_name: Lcuuid
    type: string
    for_validation: true
  - name: id
    orm_name: ID
    type: int
  - name: name
    orm_name: Name
    type: string
  - name: pod_group_ids
    orm_name: PodGroupIDs
    type: mapset.Set[int]
    is_collection: true
    comment: 'data source: pod_group_config_map_connection'
