name: config_map
orm_name: ConfigMap
cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    orm_name: Lcuuid
    type: string
    for_validation: true
  - name: id
    orm_name: ID
    type: int
  - name: name
    orm_name: Name
    type: string
  - name: pod_group_ids
    orm_name: PodGroupIDs
    type: mapset.Set[int]
    is_collection: true
    comment: 'data source: pod_group_config_map_connection'
