name: pod_group_config_map_connection
orm_name: PodGroupConfigMapConnection
cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    orm_name: Lcuuid
    type: string
    is_validation_field: true
  - name: id
    orm_name: ID
    type: int
  - name: config_map_id
    orm_name: ConfigMapID
    type: int
  - name: pod_group_id
    orm_name: PodGroupID
    type: int
