name: pod_ingress
orm_name: PodIngress

cache_diffbase:
  enabled: true
  fields:
    - name: name
      orm_name: Name
      type: string
    - name: region_lcuuid
      orm_name: Region
      type: string
    - name: az_lcuuid
      orm_name: AZ
      type: string
    - name: sub_domain_lcuuid
      orm_name: SubDomain
      type: string

cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    orm_name: Lcuuid
    type: string
    for_validation: true
  - name: id
    orm_name: ID
    type: int
  - name: name
    orm_name: Name
    type: string
  - name: region_id
    orm_name: Region
    type: int
    ref:
      resource: Region
      lookup_method: GetByLcuuid
      target_field: Id
  - name: az_id
    orm_name: AZ
    type: int
    ref:
      resource: Az
      lookup_method: GetByLcuuid
      target_field: Id
  - name: pod_namespace_id
    orm_name: PodNamespaceID
    type: int
  - name: pod_cluster_id
    orm_name: PodClusterID
    type: int
