name: pod_ingress_rule
orm_name: PodIngressRule

cache_diffbase:
  enabled: true
  fields:
    - name: sub_domain_lcuuid
      orm_name: SubDomain
      type: string

cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    orm_name: Lcuuid
    type: string
    for_validation: true
  - name: id
    orm_name: ID
    type: int
  - name: name
    orm_name: Name
    type: string
