ingester:
  exporters:
    enabled: false
    export-datas: [cbpf-net-span]
    export-data-types: [service_info]
    export-custom-k8s-labels-regexp:
    otlp-exporters:
    - enabled: true
      addr: 127.0.0.1:4317
      queue-count: 4
      queue-size: 100000
      export-batch-count: 32
      grpc-headers:
        key1: value1
        key2: value2
      export-datas: [ebpf-sys-span]
      export-data-types: [ tracing_info,network_layer,flow_info,transport_layer,application_layer,metrics ]
      export-custom-k8s-labels-regexp:
      export-only-with-traceid: true
