// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Az struct {
	ResourceBase
	Name         string
	Label        string
	RegionLcuuid string
}

func (a *Az) reset(dbItem *metadbmodel.AZ, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.RegionLcuuid = dbItem.Region
}

func NewAzCollection(t *tool.Tool) *AzCollection {
	c := new(AzCollection)
	c.collection = newCollectionBuilder[*Az]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_AZ_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.AZ { return new(metadbmodel.AZ) }).
		withCacheItemFactory(func() *Az { return new(Az) }).
		build()
	return c
}

type AzCollection struct {
	collection[*Az, *metadbmodel.AZ]
}
