// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Cen struct {
	ResourceBase
	Name       string
	VpcLcuuids []string
}

// genVpcLcuuids generates the VpcLcuuids field for Cen.
func (a *Cen) genVpcLcuuids(dbItem *metadbmodel.CEN, tool *tool.Tool) []string {
	result := []string{}
	for _, item := range dbItem.VPCIDs {
		refItem := tool.Vpc().GetById(item)
		if refItem.IsValid() {
			result = append(result, refItem.Lcuuid())
		}
	}
	return result
}

func (a *Cen) reset(dbItem *metadbmodel.CEN, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.VpcLcuuids = a.genVpcLcuuids(dbItem, tool)
}

func NewCenCollection(t *tool.Tool) *CenCollection {
	c := new(CenCollection)
	c.collection = newCollectionBuilder[*Cen]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_CEN_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.CEN { return new(metadbmodel.CEN) }).
		withCacheItemFactory(func() *Cen { return new(Cen) }).
		build()
	return c
}

type CenCollection struct {
	collection[*Cen, *metadbmodel.CEN]
}
