// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type ConfigMap struct {
	ResourceBase
	Name     string
	Data     string
	DataHash string
}

func (a *ConfigMap) reset(dbItem *metadbmodel.ConfigMap, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Data = string(dbItem.Data)
	a.DataHash = dbItem.DataHash
}

// ToLoggable converts ConfigMap to a loggable format, excluding large fields
func (a ConfigMap) ToLoggable() interface{} {
	copied := a
	copied.Data = "**HIDDEN**"
	return copied
}

func NewConfigMapCollection(t *tool.Tool) *ConfigMapCollection {
	c := new(ConfigMapCollection)
	c.collection = newCollectionBuilder[*ConfigMap]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_CONFIG_MAP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.ConfigMap { return new(metadbmodel.ConfigMap) }).
		withCacheItemFactory(func() *ConfigMap { return new(ConfigMap) }).
		build()
	return c
}

type ConfigMapCollection struct {
	collection[*ConfigMap, *metadbmodel.ConfigMap]
}
