// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type DhcpPort struct {
	ResourceBase
	Name         string
	RegionLcuuid string
	AzLcuuid     string
	VpcLcuuid    string
}

func (a *DhcpPort) reset(dbItem *metadbmodel.DHCPPort, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.VpcLcuuid = tool.Vpc().GetById(dbItem.VPCID).Lcuuid()
}

func NewDhcpPortCollection(t *tool.Tool) *DhcpPortCollection {
	c := new(DhcpPortCollection)
	c.collection = newCollectionBuilder[*DhcpPort]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_DHCP_PORT_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.DHCPPort { return new(metadbmodel.DHCPPort) }).
		withCacheItemFactory(func() *DhcpPort { return new(DhcpPort) }).
		build()
	return c
}

type DhcpPortCollection struct {
	collection[*DhcpPort, *metadbmodel.DHCPPort]
}
