// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type FloatingIp struct {
	ResourceBase
	RegionLcuuid string
	VpcLcuuid    string
}

func (a *FloatingIp) reset(dbItem *metadbmodel.FloatingIP, tool *tool.Tool) {
	a.RegionLcuuid = dbItem.Region
	a.VpcLcuuid = tool.Vpc().GetById(dbItem.VPCID).Lcuuid()
}

func NewFloatingIpCollection(t *tool.Tool) *FloatingIpCollection {
	c := new(FloatingIpCollection)
	c.collection = newCollectionBuilder[*FloatingIp]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_FLOATING_IP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.FloatingIP { return new(metadbmodel.FloatingIP) }).
		withCacheItemFactory(func() *FloatingIp { return new(FloatingIp) }).
		build()
	return c
}

type FloatingIpCollection struct {
	collection[*FloatingIp, *metadbmodel.FloatingIP]
}
