// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type {{.PublicName}} struct {
	ResourceBase
{{- if .HasStructExtension}}
	{{.PublicName}}Ext
{{- end}}
{{- range .Fields}}
{{- if .Comment}}
	{{.PublicCamelName}} {{.GoType}} // {{.Comment}}
{{- else}}
	{{.PublicCamelName}} {{.GoType}}
{{- end}}
{{- end}}
}

{{- range .Fields}}
{{- if .IsList}}

// gen{{.PublicCamelName}} generates the {{.PublicCamelName}} field for {{$.PublicName}}.
func (a *{{$.PublicName}}) gen{{.PublicCamelName}}(dbItem *metadbmodel.{{$.OrmName}}, tool *tool.Tool) {{.GoType}} {
	result := {{.GoType}}{}
	for _, item := range dbItem.{{.OrmName}} {
		refItem := tool.{{.RefResource}}().GetBy{{.RefLookupBy}}(item)
		if refItem.IsValid() {
			result = append(result, refItem.{{.RefTarget}}())
		}
	}
	return result
}
{{- end}}
{{- end}}

func (a *{{.PublicName}}) reset(dbItem *metadbmodel.{{.OrmName}}, tool *tool.Tool) {
{{- range .Fields}}
{{- if not .IsExtension}}
{{- if .IsList}}
	a.{{.PublicCamelName}} = a.gen{{.PublicCamelName}}(dbItem, tool)
{{- else if .Ref}}
	a.{{.PublicCamelName}} = tool.{{.RefResource}}().GetBy{{.RefLookupBy}}(dbItem.{{.OrmName}}).{{.RefTarget}}()
{{- else if eq .From "bytes"}}
	a.{{.PublicCamelName}} = {{.GoType}}(dbItem.{{.OrmName}})
{{- else}}
	a.{{.PublicCamelName}} = dbItem.{{.OrmName}}
{{- end}}
{{- end}}
{{- end}}
{{- if .HasExtensionField}}
	a.resetExt(dbItem, tool)
{{- end}}
}

{{- if .HasLargeField}}

// ToLoggable converts {{.PublicName}} to a loggable format, excluding large fields
func (a {{.PublicName}}) ToLoggable() interface{} {
	copied := a
{{- range .Fields}}
{{- if .IsLarge}}
	copied.{{.PublicCamelName}} = "**HIDDEN**"
{{- end}}
{{- end}}
	return copied
}
{{- end}}

func New{{.PublicName}}Collection(t *tool.Tool) *{{.PublicName}}Collection {
	c := new({{.PublicName}}Collection)
	c.collection = newCollectionBuilder[*{{.PublicName}}]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_{{ToUpper .Name}}_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.{{.OrmName}} { return new(metadbmodel.{{.OrmName}}) }).
		withCacheItemFactory(func() *{{.PublicName}} { return new({{.PublicName}}) }).
		build()
	return c
}

type {{.PublicName}}Collection struct {
	collection[*{{.PublicName}}, *metadbmodel.{{.OrmName}}]
}