// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Host struct {
	ResourceBase
	Name         string
	Ip           string
	Hostname     string
	Htype        int
	VcpuNum      int
	MemTotal     int
	ExtraInfo    string
	RegionLcuuid string
	AzLcuuid     string
}

func (a *Host) reset(dbItem *metadbmodel.Host, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Ip = dbItem.IP
	a.Hostname = dbItem.Hostname
	a.Htype = dbItem.HType
	a.VcpuNum = dbItem.VCPUNum
	a.MemTotal = dbItem.MemTotal
	a.ExtraInfo = dbItem.ExtraInfo
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
}

func NewHostCollection(t *tool.Tool) *HostCollection {
	c := new(HostCollection)
	c.collection = newCollectionBuilder[*Host]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_HOST_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Host { return new(metadbmodel.Host) }).
		withCacheItemFactory(func() *Host { return new(Host) }).
		build()
	return c
}

type HostCollection struct {
	collection[*Host, *metadbmodel.Host]
}
