// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type LanIp struct {
	ResourceBase
	SubDomainLcuuid string
}

func (a *LanIp) reset(dbItem *metadbmodel.LANIP, tool *tool.Tool) {
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewLanIpCollection(t *tool.Tool) *LanIpCollection {
	c := new(LanIpCollection)
	c.collection = newCollectionBuilder[*LanIp]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LAN_IP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LANIP { return new(metadbmodel.LANIP) }).
		withCacheItemFactory(func() *LanIp { return new(LanIp) }).
		build()
	return c
}

type LanIpCollection struct {
	collection[*LanIp, *metadbmodel.LANIP]
}
