// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Lb struct {
	ResourceBase
	Name         string
	Model        int
	Vip          string
	VpcLcuuid    string
	RegionLcuuid string
}

func (a *Lb) reset(dbItem *metadbmodel.LB, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Model = dbItem.Model
	a.Vip = dbItem.VIP
	a.VpcLcuuid = tool.Vpc().GetById(dbItem.VPCID).Lcuuid()
	a.RegionLcuuid = dbItem.Region
}

func NewLbCollection(t *tool.Tool) *LbCollection {
	c := new(LbCollection)
	c.collection = newCollectionBuilder[*Lb]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LB_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LB { return new(metadbmodel.LB) }).
		withCacheItemFactory(func() *Lb { return new(Lb) }).
		build()
	return c
}

type LbCollection struct {
	collection[*Lb, *metadbmodel.LB]
}
