// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type LbListener struct {
	ResourceBase
	Name     string
	Ips      string
	SnatIps  string
	Port     int
	Protocol string
}

func (a *LbListener) reset(dbItem *metadbmodel.LBListener, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Ips = dbItem.IPs
	a.SnatIps = dbItem.SNATIPs
	a.Port = dbItem.Port
	a.Protocol = dbItem.Protocol
}

func NewLbListenerCollection(t *tool.Tool) *LbListenerCollection {
	c := new(LbListenerCollection)
	c.collection = newCollectionBuilder[*LbListener]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LB_LISTENER_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LBListener { return new(metadbmodel.LBListener) }).
		withCacheItemFactory(func() *LbListener { return new(LbListener) }).
		build()
	return c
}

type LbListenerCollection struct {
	collection[*LbListener, *metadbmodel.LBListener]
}
