// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type LbTargetServer struct {
	ResourceBase
	Ip       string
	Port     int
	Protocol string
}

func (a *LbTargetServer) reset(dbItem *metadbmodel.LBTargetServer, tool *tool.Tool) {
	a.Ip = dbItem.IP
	a.Port = dbItem.Port
	a.Protocol = dbItem.Protocol
}

func NewLbTargetServerCollection(t *tool.Tool) *LbTargetServerCollection {
	c := new(LbTargetServerCollection)
	c.collection = newCollectionBuilder[*LbTargetServer]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LB_TARGET_SERVER_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LBTargetServer { return new(metadbmodel.LBTargetServer) }).
		withCacheItemFactory(func() *LbTargetServer { return new(LbTargetServer) }).
		build()
	return c
}

type LbTargetServerCollection struct {
	collection[*LbTargetServer, *metadbmodel.LBTargetServer]
}
