// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type LbVmConnection struct {
	ResourceBase
}

func (a *LbVmConnection) reset(dbItem *metadbmodel.LBVMConnection, tool *tool.Tool) {
}

func NewLbVmConnectionCollection(t *tool.Tool) *LbVmConnectionCollection {
	c := new(LbVmConnectionCollection)
	c.collection = newCollectionBuilder[*LbVmConnection]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LB_VM_CONNECTION_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LBVMConnection { return new(metadbmodel.LBVMConnection) }).
		withCacheItemFactory(func() *LbVmConnection { return new(LbVmConnection) }).
		build()
	return c
}

type LbVmConnectionCollection struct {
	collection[*LbVmConnection, *metadbmodel.LBVMConnection]
}
