// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type NatRule struct {
	ResourceBase
}

func (a *NatRule) reset(dbItem *metadbmodel.NATRule, tool *tool.Tool) {
}

func NewNatRuleCollection(t *tool.Tool) *NatRuleCollection {
	c := new(NatRuleCollection)
	c.collection = newCollectionBuilder[*NatRule]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_NAT_RULE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.NATRule { return new(metadbmodel.NATRule) }).
		withCacheItemFactory(func() *NatRule { return new(NatRule) }).
		build()
	return c
}

type NatRuleCollection struct {
	collection[*NatRule, *metadbmodel.NATRule]
}
