// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type NatVmConnection struct {
	ResourceBase
}

func (a *NatVmConnection) reset(dbItem *metadbmodel.NATVMConnection, tool *tool.Tool) {
}

func NewNatVmConnectionCollection(t *tool.Tool) *NatVmConnectionCollection {
	c := new(NatVmConnectionCollection)
	c.collection = newCollectionBuilder[*NatVmConnection]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_NAT_VM_CONNECTION_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.NATVMConnection { return new(metadbmodel.NATVMConnection) }).
		withCacheItemFactory(func() *NatVmConnection { return new(NatVmConnection) }).
		build()
	return c
}

type NatVmConnectionCollection struct {
	collection[*NatVmConnection, *metadbmodel.NATVMConnection]
}
