// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type NatGateway struct {
	ResourceBase
	Name         string
	FloatingIps  string
	RegionLcuuid string
}

func (a *NatGateway) reset(dbItem *metadbmodel.NATGateway, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.FloatingIps = dbItem.FloatingIPs
	a.RegionLcuuid = dbItem.Region
}

func NewNatGatewayCollection(t *tool.Tool) *NatGatewayCollection {
	c := new(NatGatewayCollection)
	c.collection = newCollectionBuilder[*NatGateway]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_NAT_GATEWAY_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.NATGateway { return new(metadbmodel.NATGateway) }).
		withCacheItemFactory(func() *NatGateway { return new(NatGateway) }).
		build()
	return c
}

type NatGatewayCollection struct {
	collection[*NatGateway, *metadbmodel.NATGateway]
}
