// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Network struct {
	ResourceBase
	Name            string
	Label           string
	TunnelId        int
	NetType         int
	SegmentationId  int
	VpcLcuuid       string
	RegionLcuuid    string
	AzLcuuid        string
	SubDomainLcuuid string
}

func (a *Network) reset(dbItem *metadbmodel.Network, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.TunnelId = dbItem.TunnelID
	a.NetType = dbItem.NetType
	a.SegmentationId = dbItem.SegmentationID
	a.VpcLcuuid = tool.Vpc().GetById(dbItem.VPCID).Lcuuid()
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewNetworkCollection(t *tool.Tool) *NetworkCollection {
	c := new(NetworkCollection)
	c.collection = newCollectionBuilder[*Network]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_NETWORK_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Network { return new(metadbmodel.Network) }).
		withCacheItemFactory(func() *Network { return new(Network) }).
		build()
	return c
}

type NetworkCollection struct {
	collection[*Network, *metadbmodel.Network]
}
