// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PeerConnection struct {
	ResourceBase
	Name string
}

func (a *PeerConnection) reset(dbItem *metadbmodel.PeerConnection, tool *tool.Tool) {
	a.Name = dbItem.Name
}

func NewPeerConnectionCollection(t *tool.Tool) *PeerConnectionCollection {
	c := new(PeerConnectionCollection)
	c.collection = newCollectionBuilder[*PeerConnection]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_PEER_CONNECTION_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PeerConnection { return new(metadbmodel.PeerConnection) }).
		withCacheItemFactory(func() *PeerConnection { return new(PeerConnection) }).
		build()
	return c
}

type PeerConnectionCollection struct {
	collection[*PeerConnection, *metadbmodel.PeerConnection]
}
