// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	"time"

	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Pod struct {
	ResourceBase
	Name                string
	Label               string
	Annotation          string
	Env                 string
	ContainerIds        string
	State               int
	CreatedAt           time.Time
	PodNodeLcuuid       string
	PodReplicaSetLcuuid string
	PodGroupLcuuid      string
	PodServiceLcuuid    string
	VpcLcuuid           string
	RegionLcuuid        string
	AzLcuuid            string
	SubDomainLcuuid     string
}

func (a *Pod) reset(dbItem *metadbmodel.Pod, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.Annotation = dbItem.Annotation
	a.Env = dbItem.ENV
	a.ContainerIds = dbItem.ContainerIDs
	a.State = dbItem.State
	a.CreatedAt = dbItem.CreatedAt
	a.PodNodeLcuuid = tool.PodNode().GetById(dbItem.PodNodeID).Lcuuid()
	a.PodReplicaSetLcuuid = tool.PodReplicaSet().GetById(dbItem.PodReplicaSetID).Lcuuid()
	a.PodGroupLcuuid = tool.PodGroup().GetById(dbItem.PodGroupID).Lcuuid()
	a.PodServiceLcuuid = tool.PodService().GetById(dbItem.PodServiceID).Lcuuid()
	a.VpcLcuuid = tool.Vpc().GetById(dbItem.VPCID).Lcuuid()
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewPodCollection(t *tool.Tool) *PodCollection {
	c := new(PodCollection)
	c.collection = newCollectionBuilder[*Pod]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Pod { return new(metadbmodel.Pod) }).
		withCacheItemFactory(func() *Pod { return new(Pod) }).
		build()
	return c
}

type PodCollection struct {
	collection[*Pod, *metadbmodel.Pod]
}
