// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodIngressRuleBackend struct {
	ResourceBase
	SubDomainLcuuid string
}

func (a *PodIngressRuleBackend) reset(dbItem *metadbmodel.PodIngressRuleBackend, tool *tool.Tool) {
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewPodIngressRuleBackendCollection(t *tool.Tool) *PodIngressRuleBackendCollection {
	c := new(PodIngressRuleBackendCollection)
	c.collection = newCollectionBuilder[*PodIngressRuleBackend]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_INGRESS_RULE_BACKEND_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodIngressRuleBackend { return new(metadbmodel.PodIngressRuleBackend) }).
		withCacheItemFactory(func() *PodIngressRuleBackend { return new(PodIngressRuleBackend) }).
		build()
	return c
}

type PodIngressRuleBackendCollection struct {
	collection[*PodIngressRuleBackend, *metadbmodel.PodIngressRuleBackend]
}
