// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodNamespace struct {
	ResourceBase
	RegionLcuuid     string
	AzLcuuid         string
	SubDomainLcuuid  string
	LearnedCloudTags map[string]string
}

func (a *PodNamespace) reset(dbItem *metadbmodel.PodNamespace, tool *tool.Tool) {
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.SubDomainLcuuid = dbItem.SubDomain
	a.LearnedCloudTags = dbItem.LearnedCloudTags
}

func NewPodNamespaceCollection(t *tool.Tool) *PodNamespaceCollection {
	c := new(PodNamespaceCollection)
	c.collection = newCollectionBuilder[*PodNamespace]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_NAMESPACE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodNamespace { return new(metadbmodel.PodNamespace) }).
		withCacheItemFactory(func() *PodNamespace { return new(PodNamespace) }).
		build()
	return c
}

type PodNamespaceCollection struct {
	collection[*PodNamespace, *metadbmodel.PodNamespace]
}
