// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodGroupConfigMapConnection struct {
	ResourceBase
}

func (a *PodGroupConfigMapConnection) reset(dbItem *metadbmodel.PodGroupConfigMapConnection, tool *tool.Tool) {
}

func NewPodGroupConfigMapConnectionCollection(t *tool.Tool) *PodGroupConfigMapConnectionCollection {
	c := new(PodGroupConfigMapConnectionCollection)
	c.collection = newCollectionBuilder[*PodGroupConfigMapConnection]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_GROUP_CONFIG_MAP_CONNECTION_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodGroupConfigMapConnection { return new(metadbmodel.PodGroupConfigMapConnection) }).
		withCacheItemFactory(func() *PodGroupConfigMapConnection { return new(PodGroupConfigMapConnection) }).
		build()
	return c
}

type PodGroupConfigMapConnectionCollection struct {
	collection[*PodGroupConfigMapConnection, *metadbmodel.PodGroupConfigMapConnection]
}
