// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodIngress struct {
	ResourceBase
	Name            string
	RegionLcuuid    string
	AzLcuuid        string
	SubDomainLcuuid string
}

func (a *PodIngress) reset(dbItem *metadbmodel.PodIngress, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewPodIngressCollection(t *tool.Tool) *PodIngressCollection {
	c := new(PodIngressCollection)
	c.collection = newCollectionBuilder[*PodIngress]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_INGRESS_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodIngress { return new(metadbmodel.PodIngress) }).
		withCacheItemFactory(func() *PodIngress { return new(PodIngress) }).
		build()
	return c
}

type PodIngressCollection struct {
	collection[*PodIngress, *metadbmodel.PodIngress]
}
