// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodGroupPort struct {
	ResourceBase
	Name            string
	SubDomainLcuuid string
}

func (a *PodGroupPort) reset(dbItem *metadbmodel.PodGroupPort, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewPodGroupPortCollection(t *tool.Tool) *PodGroupPortCollection {
	c := new(PodGroupPortCollection)
	c.collection = newCollectionBuilder[*PodGroupPort]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_GROUP_PORT_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodGroupPort { return new(metadbmodel.PodGroupPort) }).
		withCacheItemFactory(func() *PodGroupPort { return new(PodGroupPort) }).
		build()
	return c
}

type PodGroupPortCollection struct {
	collection[*PodGroupPort, *metadbmodel.PodGroupPort]
}
