// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodCluster struct {
	ResourceBase
	Name            string
	ClusterName     string
	RegionLcuuid    string
	AzLcuuid        string
	SubDomainLcuuid string
}

func (a *PodCluster) reset(dbItem *metadbmodel.PodCluster, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.ClusterName = dbItem.ClusterName
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewPodClusterCollection(t *tool.Tool) *PodClusterCollection {
	c := new(PodClusterCollection)
	c.collection = newCollectionBuilder[*PodCluster]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_CLUSTER_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodCluster { return new(metadbmodel.PodCluster) }).
		withCacheItemFactory(func() *PodCluster { return new(PodCluster) }).
		build()
	return c
}

type PodClusterCollection struct {
	collection[*PodCluster, *metadbmodel.PodCluster]
}
