// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodNode struct {
	ResourceBase
	Type            int
	State           int
	Hostname        string
	Ip              string
	VcpuNum         int
	MemTotal        int
	RegionLcuuid    string
	AzLcuuid        string
	SubDomainLcuuid string
}

func (a *PodNode) reset(dbItem *metadbmodel.PodNode, tool *tool.Tool) {
	a.Type = dbItem.Type
	a.State = dbItem.State
	a.Hostname = dbItem.Hostname
	a.Ip = dbItem.IP
	a.VcpuNum = dbItem.VCPUNum
	a.MemTotal = dbItem.MemTotal
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewPodNodeCollection(t *tool.Tool) *PodNodeCollection {
	c := new(PodNodeCollection)
	c.collection = newCollectionBuilder[*PodNode]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_NODE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodNode { return new(metadbmodel.PodNode) }).
		withCacheItemFactory(func() *PodNode { return new(PodNode) }).
		build()
	return c
}

type PodNodeCollection struct {
	collection[*PodNode, *metadbmodel.PodNode]
}
