// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodIngressRule struct {
	ResourceBase
	SubDomainLcuuid string
}

func (a *PodIngressRule) reset(dbItem *metadbmodel.PodIngressRule, tool *tool.Tool) {
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewPodIngressRuleCollection(t *tool.Tool) *PodIngressRuleCollection {
	c := new(PodIngressRuleCollection)
	c.collection = newCollectionBuilder[*PodIngressRule]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_INGRESS_RULE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodIngressRule { return new(metadbmodel.PodIngressRule) }).
		withCacheItemFactory(func() *PodIngressRule { return new(PodIngressRule) }).
		build()
	return c
}

type PodIngressRuleCollection struct {
	collection[*PodIngressRule, *metadbmodel.PodIngressRule]
}
