// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodGroup struct {
	ResourceBase
	Name            string
	Label           string
	PodNum          int
	Type            int
	Metadata        string
	MetadataHash    string
	Spec            string
	SpecHash        string
	RegionLcuuid    string
	AzLcuuid        string
	SubDomainLcuuid string
	NetworkMode     int
}

func (a *PodGroup) reset(dbItem *metadbmodel.PodGroup, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.PodNum = dbItem.PodNum
	a.Type = dbItem.Type
	a.Metadata = string(dbItem.Metadata)
	a.MetadataHash = dbItem.MetadataHash
	a.Spec = string(dbItem.Spec)
	a.SpecHash = dbItem.SpecHash
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.SubDomainLcuuid = dbItem.SubDomain
	a.NetworkMode = dbItem.NetworkMode
}

// ToLoggable converts PodGroup to a loggable format, excluding large fields
func (a PodGroup) ToLoggable() interface{} {
	copied := a
	copied.Metadata = "**HIDDEN**"
	copied.Spec = "**HIDDEN**"
	return copied
}

func NewPodGroupCollection(t *tool.Tool) *PodGroupCollection {
	c := new(PodGroupCollection)
	c.collection = newCollectionBuilder[*PodGroup]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_GROUP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodGroup { return new(metadbmodel.PodGroup) }).
		withCacheItemFactory(func() *PodGroup { return new(PodGroup) }).
		build()
	return c
}

type PodGroupCollection struct {
	collection[*PodGroup, *metadbmodel.PodGroup]
}
