// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodService struct {
	ResourceBase
	Name             string
	Label            string
	Annotation       string
	Selector         string
	ExternalIp       string
	ServiceClusterIp string
	Metadata         string
	MetadataHash     string
	Spec             string
	SpecHash         string
	PodIngressLcuuid string
	RegionLcuuid     string
	AzLcuuid         string
	SubDomainLcuuid  string
}

func (a *PodService) reset(dbItem *metadbmodel.PodService, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.Annotation = dbItem.Annotation
	a.Selector = dbItem.Selector
	a.ExternalIp = dbItem.ExternalIP
	a.ServiceClusterIp = dbItem.ServiceClusterIP
	a.Metadata = string(dbItem.Metadata)
	a.MetadataHash = dbItem.MetadataHash
	a.Spec = string(dbItem.Spec)
	a.SpecHash = dbItem.SpecHash
	a.PodIngressLcuuid = tool.PodIngress().GetById(dbItem.PodIngressID).Lcuuid()
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.SubDomainLcuuid = dbItem.SubDomain
}

// ToLoggable converts PodService to a loggable format, excluding large fields
func (a PodService) ToLoggable() interface{} {
	copied := a
	copied.Metadata = "**HIDDEN**"
	copied.Spec = "**HIDDEN**"
	return copied
}

func NewPodServiceCollection(t *tool.Tool) *PodServiceCollection {
	c := new(PodServiceCollection)
	c.collection = newCollectionBuilder[*PodService]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_SERVICE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodService { return new(metadbmodel.PodService) }).
		withCacheItemFactory(func() *PodService { return new(PodService) }).
		build()
	return c
}

type PodServiceCollection struct {
	collection[*PodService, *metadbmodel.PodService]
}
