// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodReplicaSet struct {
	ResourceBase
	Name            string
	Label           string
	PodNum          int
	RegionLcuuid    string
	AzLcuuid        string
	SubDomainLcuuid string
}

func (a *PodReplicaSet) reset(dbItem *metadbmodel.PodReplicaSet, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.PodNum = dbItem.PodNum
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewPodReplicaSetCollection(t *tool.Tool) *PodReplicaSetCollection {
	c := new(PodReplicaSetCollection)
	c.collection = newCollectionBuilder[*PodReplicaSet]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_REPLICA_SET_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodReplicaSet { return new(metadbmodel.PodReplicaSet) }).
		withCacheItemFactory(func() *PodReplicaSet { return new(PodReplicaSet) }).
		build()
	return c
}

type PodReplicaSetCollection struct {
	collection[*PodReplicaSet, *metadbmodel.PodReplicaSet]
}
