// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type PodServicePort struct {
	ResourceBase
	Name            string
	SubDomainLcuuid string
}

func (a *PodServicePort) reset(dbItem *metadbmodel.PodServicePort, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewPodServicePortCollection(t *tool.Tool) *PodServicePortCollection {
	c := new(PodServicePortCollection)
	c.collection = newCollectionBuilder[*PodServicePort]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_SERVICE_PORT_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodServicePort { return new(metadbmodel.PodServicePort) }).
		withCacheItemFactory(func() *PodServicePort { return new(PodServicePort) }).
		build()
	return c
}

type PodServicePortCollection struct {
	collection[*PodServicePort, *metadbmodel.PodServicePort]
}
