// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Process struct {
	ResourceBase
	Name        string
	OsAppTags   string
	ContainerId string
	DeviceType  int
	DeviceId    int
}

func (a *Process) reset(dbItem *metadbmodel.Process, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.OsAppTags = dbItem.OSAPPTags
	a.ContainerId = dbItem.ContainerID
	a.DeviceType = dbItem.DeviceType
	a.DeviceId = dbItem.DeviceID
}

func NewProcessCollection(t *tool.Tool) *ProcessCollection {
	c := new(ProcessCollection)
	c.collection = newCollectionBuilder[*Process]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_PROCESS_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Process { return new(metadbmodel.Process) }).
		withCacheItemFactory(func() *Process { return new(Process) }).
		build()
	return c
}

type ProcessCollection struct {
	collection[*Process, *metadbmodel.Process]
}
