// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type RdsInstance struct {
	ResourceBase
	Name         string
	State        int
	Series       int
	Model        int
	VpcLcuuid    string
	RegionLcuuid string
	AzLcuuid     string
}

func (a *RdsInstance) reset(dbItem *metadbmodel.RDSInstance, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.State = dbItem.State
	a.Series = dbItem.Series
	a.Model = dbItem.Model
	a.VpcLcuuid = tool.Vpc().GetById(dbItem.VPCID).Lcuuid()
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
}

func NewRdsInstanceCollection(t *tool.Tool) *RdsInstanceCollection {
	c := new(RdsInstanceCollection)
	c.collection = newCollectionBuilder[*RdsInstance]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_RDS_INSTANCE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.RDSInstance { return new(metadbmodel.RDSInstance) }).
		withCacheItemFactory(func() *RdsInstance { return new(RdsInstance) }).
		build()
	return c
}

type RdsInstanceCollection struct {
	collection[*RdsInstance, *metadbmodel.RDSInstance]
}
