// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type RedisInstance struct {
	ResourceBase
	Name         string
	State        int
	PublicHost   string
	RegionLcuuid string
	AzLcuuid     string
}

func (a *RedisInstance) reset(dbItem *metadbmodel.RedisInstance, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.State = dbItem.State
	a.PublicHost = dbItem.PublicHost
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
}

func NewRedisInstanceCollection(t *tool.Tool) *RedisInstanceCollection {
	c := new(RedisInstanceCollection)
	c.collection = newCollectionBuilder[*RedisInstance]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_REDIS_INSTANCE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.RedisInstance { return new(metadbmodel.RedisInstance) }).
		withCacheItemFactory(func() *RedisInstance { return new(RedisInstance) }).
		build()
	return c
}

type RedisInstanceCollection struct {
	collection[*RedisInstance, *metadbmodel.RedisInstance]
}
