// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Region struct {
	ResourceBase
	Name  string
	Label string
}

func (a *Region) reset(dbItem *metadbmodel.Region, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
}

func NewRegionCollection(t *tool.Tool) *RegionCollection {
	c := new(RegionCollection)
	c.collection = newCollectionBuilder[*Region]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_REGION_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Region { return new(metadbmodel.Region) }).
		withCacheItemFactory(func() *Region { return new(Region) }).
		build()
	return c
}

type RegionCollection struct {
	collection[*Region, *metadbmodel.Region]
}
