// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type RoutingTable struct {
	ResourceBase
	Destination string
	Nexthop     string
	NexthopType string
}

func (a *RoutingTable) reset(dbItem *metadbmodel.RoutingTable, tool *tool.Tool) {
	a.Destination = dbItem.Destination
	a.Nexthop = dbItem.Nexthop
	a.NexthopType = dbItem.NexthopType
}

func NewRoutingTableCollection(t *tool.Tool) *RoutingTableCollection {
	c := new(RoutingTableCollection)
	c.collection = newCollectionBuilder[*RoutingTable]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_ROUTING_TABLE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.RoutingTable { return new(metadbmodel.RoutingTable) }).
		withCacheItemFactory(func() *RoutingTable { return new(RoutingTable) }).
		build()
	return c
}

type RoutingTableCollection struct {
	collection[*RoutingTable, *metadbmodel.RoutingTable]
}
