// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type SubDomain struct {
	ResourceBase
	Name string
}

func (a *SubDomain) reset(dbItem *metadbmodel.SubDomain, tool *tool.Tool) {
	a.Name = dbItem.Name
}

func NewSubDomainCollection(t *tool.Tool) *SubDomainCollection {
	c := new(SubDomainCollection)
	c.collection = newCollectionBuilder[*SubDomain]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_SUB_DOMAIN_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.SubDomain { return new(metadbmodel.SubDomain) }).
		withCacheItemFactory(func() *SubDomain { return new(SubDomain) }).
		build()
	return c
}

type SubDomainCollection struct {
	collection[*SubDomain, *metadbmodel.SubDomain]
}
