// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Subnet struct {
	ResourceBase
	Name            string
	Label           string
	SubDomainLcuuid string
}

func (a *Subnet) reset(dbItem *metadbmodel.Subnet, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewSubnetCollection(t *tool.Tool) *SubnetCollection {
	c := new(SubnetCollection)
	c.collection = newCollectionBuilder[*Subnet]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_SUBNET_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Subnet { return new(metadbmodel.Subnet) }).
		withCacheItemFactory(func() *Subnet { return new(Subnet) }).
		build()
	return c
}

type SubnetCollection struct {
	collection[*Subnet, *metadbmodel.Subnet]
}
