// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Vinterface struct {
	ResourceBase
	VinterfaceExt
	Name            string
	Type            int
	TapMac          string
	NetnsId         uint32
	VtapId          uint32
	VpcId           int
	DeviceType      int
	DeviceLcuuid    string
	NetworkLcuuid   string
	RegionLcuuid    string
	SubDomainLcuuid string
}

func (a *Vinterface) reset(dbItem *metadbmodel.VInterface, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Type = dbItem.Type
	a.TapMac = dbItem.TapMac
	a.NetnsId = dbItem.NetnsID
	a.VtapId = dbItem.VtapID
	a.VpcId = dbItem.VPCID
	a.DeviceType = dbItem.DeviceType
	a.NetworkLcuuid = tool.Network().GetById(dbItem.NetworkID).Lcuuid()
	a.RegionLcuuid = dbItem.Region
	a.SubDomainLcuuid = dbItem.SubDomain
	a.resetExt(dbItem, tool)
}

func NewVinterfaceCollection(t *tool.Tool) *VinterfaceCollection {
	c := new(VinterfaceCollection)
	c.collection = newCollectionBuilder[*Vinterface]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VINTERFACE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VInterface { return new(metadbmodel.VInterface) }).
		withCacheItemFactory(func() *Vinterface { return new(Vinterface) }).
		build()
	return c
}

type VinterfaceCollection struct {
	collection[*Vinterface, *metadbmodel.VInterface]
}
