// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Vip struct {
	ResourceBase
	Ip     string
	VtapId uint32
}

func (a *Vip) reset(dbItem *metadbmodel.VIP, tool *tool.Tool) {
	a.Ip = dbItem.IP
	a.VtapId = dbItem.VTapID
}

func NewVipCollection(t *tool.Tool) *VipCollection {
	c := new(VipCollection)
	c.collection = newCollectionBuilder[*Vip]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VIP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VIP { return new(metadbmodel.VIP) }).
		withCacheItemFactory(func() *Vip { return new(Vip) }).
		build()
	return c
}

type VipCollection struct {
	collection[*Vip, *metadbmodel.VIP]
}
