// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Vm struct {
	ResourceBase
	Name             string
	Label            string
	Ip               string
	Hostname         string
	State            int
	Htype            int
	LaunchServer     string
	VpcLcuuid        string
	RegionLcuuid     string
	AzLcuuid         string
	LearnedCloudTags map[string]string
	NetworkLcuuid    string
	HostId           int
}

func (a *Vm) reset(dbItem *metadbmodel.VM, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.Ip = dbItem.IP
	a.Hostname = dbItem.Hostname
	a.State = dbItem.State
	a.Htype = dbItem.HType
	a.LaunchServer = dbItem.LaunchServer
	a.VpcLcuuid = tool.Vpc().GetById(dbItem.VPCID).Lcuuid()
	a.RegionLcuuid = dbItem.Region
	a.AzLcuuid = dbItem.AZ
	a.LearnedCloudTags = dbItem.LearnedCloudTags
	a.NetworkLcuuid = tool.Network().GetById(dbItem.NetworkID).Lcuuid()
	a.HostId = tool.Host().GetByIp(dbItem.LaunchServer).Id()
}

func NewVmCollection(t *tool.Tool) *VmCollection {
	c := new(VmCollection)
	c.collection = newCollectionBuilder[*Vm]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VM_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VM { return new(metadbmodel.VM) }).
		withCacheItemFactory(func() *Vm { return new(Vm) }).
		build()
	return c
}

type VmCollection struct {
	collection[*Vm, *metadbmodel.VM]
}
