// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type VmPodNodeConnection struct {
	ResourceBase
	SubDomainLcuuid string
}

func (a *VmPodNodeConnection) reset(dbItem *metadbmodel.VMPodNodeConnection, tool *tool.Tool) {
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewVmPodNodeConnectionCollection(t *tool.Tool) *VmPodNodeConnectionCollection {
	c := new(VmPodNodeConnectionCollection)
	c.collection = newCollectionBuilder[*VmPodNodeConnection]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VM_POD_NODE_CONNECTION_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VMPodNodeConnection { return new(metadbmodel.VMPodNodeConnection) }).
		withCacheItemFactory(func() *VmPodNodeConnection { return new(VmPodNodeConnection) }).
		build()
	return c
}

type VmPodNodeConnectionCollection struct {
	collection[*VmPodNodeConnection, *metadbmodel.VMPodNodeConnection]
}
