// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Vpc struct {
	ResourceBase
	Name         string
	Label        string
	TunnelId     int
	Cidr         string
	RegionLcuuid string
	Owner        string
}

func (a *Vpc) reset(dbItem *metadbmodel.VPC, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.TunnelId = dbItem.TunnelID
	a.Cidr = dbItem.CIDR
	a.RegionLcuuid = dbItem.Region
	a.Owner = dbItem.Owner
}

func NewVpcCollection(t *tool.Tool) *VpcCollection {
	c := new(VpcCollection)
	c.collection = newCollectionBuilder[*Vpc]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VPC_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VPC { return new(metadbmodel.VPC) }).
		withCacheItemFactory(func() *Vpc { return new(Vpc) }).
		build()
	return c
}

type VpcCollection struct {
	collection[*Vpc, *metadbmodel.VPC]
}
