// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type Vrouter struct {
	ResourceBase
	Name         string
	Label        string
	VpcLcuuid    string
	RegionLcuuid string
}

func (a *Vrouter) reset(dbItem *metadbmodel.VRouter, tool *tool.Tool) {
	a.Name = dbItem.Name
	a.Label = dbItem.Label
	a.VpcLcuuid = tool.Vpc().GetById(dbItem.VPCID).Lcuuid()
	a.RegionLcuuid = dbItem.Region
}

func NewVrouterCollection(t *tool.Tool) *VrouterCollection {
	c := new(VrouterCollection)
	c.collection = newCollectionBuilder[*Vrouter]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VROUTER_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VRouter { return new(metadbmodel.VRouter) }).
		withCacheItemFactory(func() *Vrouter { return new(Vrouter) }).
		build()
	return c
}

type VrouterCollection struct {
	collection[*Vrouter, *metadbmodel.VRouter]
}
