// Code generated by generator; DO NOT EDIT.

package diffbase

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
	"github.com/deepflowio/deepflow/server/controller/recorder/cache/tool"
)

type WanIp struct {
	ResourceBase
	RegionLcuuid    string
	SubDomainLcuuid string
}

func (a *WanIp) reset(dbItem *metadbmodel.WANIP, tool *tool.Tool) {
	a.RegionLcuuid = dbItem.Region
	a.SubDomainLcuuid = dbItem.SubDomain
}

func NewWanIpCollection(t *tool.Tool) *WanIpCollection {
	c := new(WanIpCollection)
	c.collection = newCollectionBuilder[*WanIp]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_WAN_IP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.WANIP { return new(metadbmodel.WANIP) }).
		withCacheItemFactory(func() *WanIp { return new(WanIp) }).
		build()
	return c
}

type WanIpCollection struct {
	collection[*WanIp, *metadbmodel.WANIP]
}
