ALTER TABLE host_device ALTER COLUMN name SET DEFAULT '';
ALTER TABLE host_device ALTER COLUMN alias SET DEFAULT '';
ALTER TABLE host_device ALTER COLUMN description SET DEFAULT '';
ALTER TABLE host_device ALTER COLUMN ip SET DEFAULT '';
ALTER TABLE host_device ALTER COLUMN user_name SET DEFAULT '';
ALTER TABLE host_device ALTER COLUMN user_passwd SET DEFAULT '';

ALTER TABLE vnet ALTER COLUMN name SET DEFAULT '';
ALTER TABLE vnet ALTER COLUMN label SET DEFAULT '';
ALTER TABLE vnet ALTER COLUMN description SET DEFAULT '';
ALTER TABLE vnet ALTER COLUMN gw_launch_server SET DEFAULT '';
ALTER TABLE vnet ALTER COLUMN region SET DEFAULT '';

ALTER TABLE security_group ALTER COLUMN name SET DEFAULT '';
ALTER TABLE security_group ALTER COLUMN alias SET DEFAULT '';
ALTER TABLE security_group ALTER COLUMN region SET DEFAULT '';

ALTER TABLE security_group_rule ALTER COLUMN protocol SET DEFAULT '';

ALTER TABLE vl2 ALTER COLUMN alias SET DEFAULT '';
ALTER TABLE vl2 ALTER COLUMN description SET DEFAULT '';
ALTER TABLE vl2 ALTER COLUMN sub_domain SET DEFAULT '';
ALTER TABLE vl2 ALTER COLUMN region SET DEFAULT '';

ALTER TABLE vl2_net ALTER COLUMN prefix SET DEFAULT '';
ALTER TABLE vl2_net ALTER COLUMN netmask SET DEFAULT '';
ALTER TABLE vl2_net ALTER COLUMN name SET DEFAULT '';
ALTER TABLE vl2_net ALTER COLUMN sub_domain SET DEFAULT '';


ALTER TABLE vinterface ALTER COLUMN name SET DEFAULT '';
ALTER TABLE vinterface ALTER COLUMN sub_domain SET DEFAULT '';
ALTER TABLE vinterface ALTER COLUMN region SET DEFAULT '';

ALTER TABLE vinterface_ip ALTER COLUMN ip SET DEFAULT '';
ALTER TABLE vinterface_ip ALTER COLUMN netmask SET DEFAULT '';
ALTER TABLE vinterface_ip ALTER COLUMN gateway SET DEFAULT '';
ALTER TABLE vinterface_ip ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE ip_resource ALTER COLUMN region SET DEFAULT '';
ALTER TABLE ip_resource ALTER COLUMN ip SET DEFAULT '';

ALTER TABLE dhcp_port ALTER COLUMN name SET DEFAULT '';
ALTER TABLE dhcp_port ALTER COLUMN region SET DEFAULT '';

ALTER TABLE az ALTER COLUMN name SET DEFAULT '';
ALTER TABLE az ALTER COLUMN region SET DEFAULT '';
ALTER TABLE az ALTER COLUMN domain SET DEFAULT '';

ALTER TABLE sub_domain ALTER COLUMN domain SET DEFAULT '';
ALTER TABLE sub_domain ALTER COLUMN name SET DEFAULT '';
ALTER TABLE sub_domain ALTER COLUMN cluster_id SET DEFAULT '';

ALTER TABLE region ALTER COLUMN name SET DEFAULT '';

ALTER TABLE epc ALTER COLUMN alias SET DEFAULT '';
ALTER TABLE epc ALTER COLUMN uid SET DEFAULT '';

ALTER TABLE peer_connection ALTER COLUMN label SET DEFAULT '';

ALTER TABLE cen ALTER COLUMN label SET DEFAULT '';
ALTER TABLE cen ALTER COLUMN alias SET DEFAULT '';

ALTER TABLE nat_gateway ALTER COLUMN label SET DEFAULT '';
ALTER TABLE nat_gateway ALTER COLUMN uid SET DEFAULT '';

ALTER TABLE nat_rule ALTER COLUMN type SET DEFAULT '';
ALTER TABLE nat_rule ALTER COLUMN protocol SET DEFAULT '';
ALTER TABLE nat_rule ALTER COLUMN floating_ip SET DEFAULT '';
ALTER TABLE nat_rule ALTER COLUMN fixed_ip SET DEFAULT '';


ALTER TABLE redis_instance ALTER COLUMN label SET DEFAULT '';
ALTER TABLE redis_instance ALTER COLUMN uid SET DEFAULT '';

ALTER TABLE rds_instance ALTER COLUMN label SET DEFAULT '';
ALTER TABLE rds_instance ALTER COLUMN uid SET DEFAULT '';

ALTER TABLE lb ALTER COLUMN label SET DEFAULT '';
ALTER TABLE lb ALTER COLUMN uid SET DEFAULT '';

ALTER TABLE lb_listener ALTER COLUMN label SET DEFAULT '';

ALTER TABLE lb_target_server ALTER COLUMN ip SET DEFAULT '';

ALTER TABLE vm_pod_node_connection ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE pod_cluster ALTER COLUMN region SET DEFAULT '';
ALTER TABLE pod_cluster ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE pod_node ALTER COLUMN alias SET DEFAULT '';
ALTER TABLE pod_node ALTER COLUMN ip SET DEFAULT '';
ALTER TABLE pod_node ALTER COLUMN region SET DEFAULT '';
ALTER TABLE pod_node ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE pod ALTER COLUMN alias SET DEFAULT '';
ALTER TABLE pod ALTER COLUMN region SET DEFAULT '';
ALTER TABLE pod ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE pod_rs ALTER COLUMN alias SET DEFAULT '';
ALTER TABLE pod_rs ALTER COLUMN region SET DEFAULT '';
ALTER TABLE pod_rs ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE pod_group ALTER COLUMN alias SET DEFAULT '';
ALTER TABLE pod_group ALTER COLUMN region SET DEFAULT '';
ALTER TABLE pod_group ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE pod_namespace ALTER COLUMN alias SET DEFAULT '';
ALTER TABLE pod_namespace ALTER COLUMN region SET DEFAULT '';
ALTER TABLE pod_namespace ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE pod_service ALTER COLUMN region SET DEFAULT '';
ALTER TABLE pod_service ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE pod_service_port ALTER COLUMN protocol SET DEFAULT '';
ALTER TABLE pod_service_port ALTER COLUMN sub_domain SET DEFAULT '';

ALTER TABLE pod_group_port ALTER COLUMN protocol SET DEFAULT '';
ALTER TABLE pod_group_port ALTER COLUMN sub_domain SET DEFAULT '';

UPDATE db_version SET version = '6.1.8.0';
