// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedAzs struct {
	MetadbItems[metadbmodel.AZ]
	addition[AddNoneAddition]
}

type DeletedAzs struct {
	Lcuuids
	MetadbItems[metadbmodel.AZ]
	addition[DeleteNoneAddition]
}

type UpdatedAzFields struct {
	Key
	Name         fieldDetail[string]
	Label        fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedAz struct {
	Fields[UpdatedAzFields]
	MetadbData[metadbmodel.AZ]
}
