// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedCens struct {
	MetadbItems[metadbmodel.CEN]
	addition[AddNoneAddition]
}

type DeletedCens struct {
	Lcuuids
	MetadbItems[metadbmodel.CEN]
	addition[DeleteNoneAddition]
}

type UpdatedCenFields struct {
	Key
	Name       fieldDetail[string]
	VpcIds     fieldDetail[[]int]
	VpcLcuuids fieldDetail[[]string]
}

type UpdatedCen struct {
	Fields[UpdatedCenFields]
	MetadbData[metadbmodel.CEN]
}
