// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedConfigMaps struct {
	MetadbItems[metadbmodel.ConfigMap]
	addition[AddNoneAddition]
}

type DeletedConfigMaps struct {
	Lcuuids
	MetadbItems[metadbmodel.ConfigMap]
	addition[DeleteNoneAddition]
}

type UpdatedConfigMapFields struct {
	Key
	Name fieldDetail[string]
	Data fieldDetail[string]
}

type UpdatedConfigMap struct {
	Fields[UpdatedConfigMapFields]
	MetadbData[metadbmodel.ConfigMap]
}
