// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedCustomServices struct {
	MetadbItems[metadbmodel.CustomService]
	addition[AddNoneAddition]
}

type DeletedCustomServices struct {
	Lcuuids
	MetadbItems[metadbmodel.CustomService]
	addition[DeleteNoneAddition]
}

type UpdatedCustomServiceFields struct {
	Key
	Name fieldDetail[string]
}

type UpdatedCustomService struct {
	Fields[UpdatedCustomServiceFields]
	MetadbData[metadbmodel.CustomService]
}
