// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedDhcpPorts struct {
	MetadbItems[metadbmodel.DHCPPort]
	addition[AddNoneAddition]
}

type DeletedDhcpPorts struct {
	Lcuuids
	MetadbItems[metadbmodel.DHCPPort]
	addition[DeleteNoneAddition]
}

type UpdatedDhcpPortFields struct {
	Key
	Name         fieldDetail[string]
	VpcId        fieldDetail[int]
	VpcLcuuid    fieldDetail[string]
	AzLcuuid     fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedDhcpPort struct {
	Fields[UpdatedDhcpPortFields]
	MetadbData[metadbmodel.DHCPPort]
}
