// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedFloatingIps struct {
	MetadbItems[metadbmodel.FloatingIP]
	addition[AddNoneAddition]
}

type DeletedFloatingIps struct {
	Lcuuids
	MetadbItems[metadbmodel.FloatingIP]
	addition[DeleteNoneAddition]
}

type UpdatedFloatingIpFields struct {
	Key
	VpcId        fieldDetail[int]
	VpcLcuuid    fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedFloatingIp struct {
	Fields[UpdatedFloatingIpFields]
	MetadbData[metadbmodel.FloatingIP]
}
