// Code generated by generator; DO NOT EDIT.

package message

import (
{{- if .HasTimeImport}}
	"time"
{{end}}
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type Added{{pluralize .PublicName}} struct {
	MetadbItems[metadbmodel.{{.OrmName}}]
	addition[{{.AddAddition}}]
}

type Deleted{{pluralize .PublicName}} struct {
	Lcuuids
	MetadbItems[metadbmodel.{{.OrmName}}]
	addition[{{.DeleteAddition}}]
}

type Updated{{.PublicName}}Fields struct {
	Key
{{- range .Fields}}
	{{.PublicCamelName}} fieldDetail[{{.GoType}}]
{{- end}}
}

type Updated{{.PublicName}} struct {
	Fields[Updated{{.PublicName}}Fields]
	MetadbData[metadbmodel.{{.OrmName}}]
}
