// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedHosts struct {
	MetadbItems[metadbmodel.Host]
	addition[AddNoneAddition]
}

type DeletedHosts struct {
	Lcuuids
	MetadbItems[metadbmodel.Host]
	addition[DeleteNoneAddition]
}

type UpdatedHostFields struct {
	Key
	Name         fieldDetail[string]
	Ip           fieldDetail[string]
	Uid          fieldDetail[string]
	Htype        fieldDetail[int]
	VcpuNum      fieldDetail[int]
	MemTotal     fieldDetail[int]
	ExtraInfo    fieldDetail[string]
	Hostname     fieldDetail[string]
	AzLcuuid     fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedHost struct {
	Fields[UpdatedHostFields]
	MetadbData[metadbmodel.Host]
}
