// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedLanIps struct {
	MetadbItems[metadbmodel.LANIP]
	addition[AddNoneAddition]
}

type DeletedLanIps struct {
	Lcuuids
	MetadbItems[metadbmodel.LANIP]
	addition[DeleteNoneAddition]
}

type UpdatedLanIpFields struct {
	Key
	SubnetId     fieldDetail[int]
	SubnetLcuuid fieldDetail[string]
}

type UpdatedLanIp struct {
	Fields[UpdatedLanIpFields]
	MetadbData[metadbmodel.LANIP]
}
