// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedLbs struct {
	MetadbItems[metadbmodel.LB]
	addition[AddNoneAddition]
}

type DeletedLbs struct {
	Lcuuids
	MetadbItems[metadbmodel.LB]
	addition[DeleteNoneAddition]
}

type UpdatedLbFields struct {
	Key
	Name         fieldDetail[string]
	Uid          fieldDetail[string]
	Model        fieldDetail[int]
	Vip          fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedLb struct {
	Fields[UpdatedLbFields]
	MetadbData[metadbmodel.LB]
}
