// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedLbListeners struct {
	MetadbItems[metadbmodel.LBListener]
	addition[AddNoneAddition]
}

type DeletedLbListeners struct {
	Lcuuids
	MetadbItems[metadbmodel.LBListener]
	addition[DeleteNoneAddition]
}

type UpdatedLbListenerFields struct {
	Key
	Name     fieldDetail[string]
	Ips      fieldDetail[string]
	SnatIps  fieldDetail[string]
	Port     fieldDetail[int]
	Protocol fieldDetail[string]
}

type UpdatedLbListener struct {
	Fields[UpdatedLbListenerFields]
	MetadbData[metadbmodel.LBListener]
}
