// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedLbTargetServers struct {
	MetadbItems[metadbmodel.LBTargetServer]
	addition[AddNoneAddition]
}

type DeletedLbTargetServers struct {
	Lcuuids
	MetadbItems[metadbmodel.LBTargetServer]
	addition[DeleteNoneAddition]
}

type UpdatedLbTargetServerFields struct {
	Key
	Ip       fieldDetail[string]
	Port     fieldDetail[int]
	Protocol fieldDetail[string]
}

type UpdatedLbTargetServer struct {
	Fields[UpdatedLbTargetServerFields]
	MetadbData[metadbmodel.LBTargetServer]
}
