// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedLbVmConnections struct {
	MetadbItems[metadbmodel.LBVMConnection]
	addition[AddNoneAddition]
}

type DeletedLbVmConnections struct {
	Lcuuids
	MetadbItems[metadbmodel.LBVMConnection]
	addition[DeleteNoneAddition]
}

type UpdatedLbVmConnectionFields struct {
	Key
}

type UpdatedLbVmConnection struct {
	Fields[UpdatedLbVmConnectionFields]
	MetadbData[metadbmodel.LBVMConnection]
}
