// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedNatRules struct {
	MetadbItems[metadbmodel.NATRule]
	addition[AddNoneAddition]
}

type DeletedNatRules struct {
	Lcuuids
	MetadbItems[metadbmodel.NATRule]
	addition[DeleteNoneAddition]
}

type UpdatedNatRuleFields struct {
	Key
}

type UpdatedNatRule struct {
	Fields[UpdatedNatRuleFields]
	MetadbData[metadbmodel.NATRule]
}
