// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedNatGateways struct {
	MetadbItems[metadbmodel.NATGateway]
	addition[AddNoneAddition]
}

type DeletedNatGateways struct {
	Lcuuids
	MetadbItems[metadbmodel.NATGateway]
	addition[DeleteNoneAddition]
}

type UpdatedNatGatewayFields struct {
	Key
	Name         fieldDetail[string]
	FloatingIps  fieldDetail[string]
	RegionLcuuid fieldDetail[string]
	Uid          fieldDetail[string]
}

type UpdatedNatGateway struct {
	Fields[UpdatedNatGatewayFields]
	MetadbData[metadbmodel.NATGateway]
}
