// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedNatVmConnections struct {
	MetadbItems[metadbmodel.NATVMConnection]
	addition[AddNoneAddition]
}

type DeletedNatVmConnections struct {
	Lcuuids
	MetadbItems[metadbmodel.NATVMConnection]
	addition[DeleteNoneAddition]
}

type UpdatedNatVmConnectionFields struct {
	Key
}

type UpdatedNatVmConnection struct {
	Fields[UpdatedNatVmConnectionFields]
	MetadbData[metadbmodel.NATVMConnection]
}
