// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedNetworks struct {
	MetadbItems[metadbmodel.Network]
	addition[AddNoneAddition]
}

type DeletedNetworks struct {
	Lcuuids
	MetadbItems[metadbmodel.Network]
	addition[DeleteNoneAddition]
}

type UpdatedNetworkFields struct {
	Key
	Name           fieldDetail[string]
	Label          fieldDetail[string]
	TunnelId       fieldDetail[int]
	SegmentationId fieldDetail[int]
	NetType        fieldDetail[int]
	VpcId          fieldDetail[int]
	VpcLcuuid      fieldDetail[string]
	AzLcuuid       fieldDetail[string]
	RegionLcuuid   fieldDetail[string]
}

type UpdatedNetwork struct {
	Fields[UpdatedNetworkFields]
	MetadbData[metadbmodel.Network]
}
