// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPeerConnections struct {
	MetadbItems[metadbmodel.PeerConnection]
	addition[AddNoneAddition]
}

type DeletedPeerConnections struct {
	Lcuuids
	MetadbItems[metadbmodel.PeerConnection]
	addition[DeleteNoneAddition]
}

type UpdatedPeerConnectionFields struct {
	Key
	Name fieldDetail[string]
}

type UpdatedPeerConnection struct {
	Fields[UpdatedPeerConnectionFields]
	MetadbData[metadbmodel.PeerConnection]
}
