// Code generated by generator; DO NOT EDIT.

package message

import (
	"time"

	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPods struct {
	MetadbItems[metadbmodel.Pod]
	addition[AddNoneAddition]
}

type DeletedPods struct {
	Lcuuids
	MetadbItems[metadbmodel.Pod]
	addition[DeleteNoneAddition]
}

type UpdatedPodFields struct {
	Key
	Name                fieldDetail[string]
	Label               fieldDetail[string]
	State               fieldDetail[int]
	Annotation          fieldDetail[string]
	Env                 fieldDetail[string]
	ContainerIds        fieldDetail[string]
	CreatedAt           fieldDetail[time.Time]
	PodGroupId          fieldDetail[int]
	PodServiceId        fieldDetail[int]
	PodGroupLcuuid      fieldDetail[string]
	PodServiceLcuuid    fieldDetail[string]
	PodReplicaSetId     fieldDetail[int]
	PodReplicaSetLcuuid fieldDetail[string]
	PodNodeId           fieldDetail[int]
	PodNodeLcuuid       fieldDetail[string]
	VpcId               fieldDetail[int]
	VpcLcuuid           fieldDetail[string]
	AzLcuuid            fieldDetail[string]
	RegionLcuuid        fieldDetail[string]
	PodNamespaceId      fieldDetail[int]
	PodClusterId        fieldDetail[int]
}

type UpdatedPod struct {
	Fields[UpdatedPodFields]
	MetadbData[metadbmodel.Pod]
}
