// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodNodes struct {
	MetadbItems[metadbmodel.PodNode]
	addition[AddNoneAddition]
}

type DeletedPodNodes struct {
	Lcuuids
	MetadbItems[metadbmodel.PodNode]
	addition[DeleteNoneAddition]
}

type UpdatedPodNodeFields struct {
	Key
	Type         fieldDetail[int]
	State        fieldDetail[int]
	Hostname     fieldDetail[string]
	Ip           fieldDetail[string]
	VcpuNum      fieldDetail[int]
	MemTotal     fieldDetail[int]
	AzLcuuid     fieldDetail[string]
	RegionLcuuid fieldDetail[string]
	Name         fieldDetail[string]
}

type UpdatedPodNode struct {
	Fields[UpdatedPodNodeFields]
	MetadbData[metadbmodel.PodNode]
}
