// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodNamespaces struct {
	MetadbItems[metadbmodel.PodNamespace]
	addition[AddNoneAddition]
}

type DeletedPodNamespaces struct {
	Lcuuids
	MetadbItems[metadbmodel.PodNamespace]
	addition[DeleteNoneAddition]
}

type UpdatedPodNamespaceFields struct {
	Key
	LearnedCloudTags fieldDetail[map[string]string]
	CustomCloudTags  fieldDetail[map[string]string]
	AzLcuuid         fieldDetail[string]
	RegionLcuuid     fieldDetail[string]
	Name             fieldDetail[string]
	PodClusterId     fieldDetail[int]
}

type UpdatedPodNamespace struct {
	Fields[UpdatedPodNamespaceFields]
	MetadbData[metadbmodel.PodNamespace]
}
