// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodServices struct {
	MetadbItems[metadbmodel.PodService]
	addition[AddNoneAddition]
}

type DeletedPodServices struct {
	Lcuuids
	MetadbItems[metadbmodel.PodService]
	addition[DeleteNoneAddition]
}

type UpdatedPodServiceFields struct {
	Key
	Name             fieldDetail[string]
	Label            fieldDetail[string]
	Annotation       fieldDetail[string]
	Selector         fieldDetail[string]
	ExternalIp       fieldDetail[string]
	ServiceClusterIp fieldDetail[string]
	Metadata         fieldDetail[string]
	Spec             fieldDetail[string]
	PodIngressId     fieldDetail[int]
	PodIngressLcuuid fieldDetail[string]
	AzLcuuid         fieldDetail[string]
	RegionLcuuid     fieldDetail[string]
	PodNamespaceId   fieldDetail[int]
	VpcId            fieldDetail[int]
	PodClusterId     fieldDetail[int]
}

type UpdatedPodService struct {
	Fields[UpdatedPodServiceFields]
	MetadbData[metadbmodel.PodService]
}
