// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodGroupConfigMapConnections struct {
	MetadbItems[metadbmodel.PodGroupConfigMapConnection]
	addition[AddNoneAddition]
}

type DeletedPodGroupConfigMapConnections struct {
	Lcuuids
	MetadbItems[metadbmodel.PodGroupConfigMapConnection]
	addition[DeleteNoneAddition]
}

type UpdatedPodGroupConfigMapConnectionFields struct {
	Key
}

type UpdatedPodGroupConfigMapConnection struct {
	Fields[UpdatedPodGroupConfigMapConnectionFields]
	MetadbData[metadbmodel.PodGroupConfigMapConnection]
}
