// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodGroupPorts struct {
	MetadbItems[metadbmodel.PodGroupPort]
	addition[AddNoneAddition]
}

type DeletedPodGroupPorts struct {
	Lcuuids
	MetadbItems[metadbmodel.PodGroupPort]
	addition[DeleteNoneAddition]
}

type UpdatedPodGroupPortFields struct {
	Key
	Name fieldDetail[string]
}

type UpdatedPodGroupPort struct {
	Fields[UpdatedPodGroupPortFields]
	MetadbData[metadbmodel.PodGroupPort]
}
