// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodServicePorts struct {
	MetadbItems[metadbmodel.PodServicePort]
	addition[AddNoneAddition]
}

type DeletedPodServicePorts struct {
	Lcuuids
	MetadbItems[metadbmodel.PodServicePort]
	addition[DeleteNoneAddition]
}

type UpdatedPodServicePortFields struct {
	Key
	Name fieldDetail[string]
}

type UpdatedPodServicePort struct {
	Fields[UpdatedPodServicePortFields]
	MetadbData[metadbmodel.PodServicePort]
}
