// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodIngressRuleBackends struct {
	MetadbItems[metadbmodel.PodIngressRuleBackend]
	addition[AddNoneAddition]
}

type DeletedPodIngressRuleBackends struct {
	Lcuuids
	MetadbItems[metadbmodel.PodIngressRuleBackend]
	addition[DeleteNoneAddition]
}

type UpdatedPodIngressRuleBackendFields struct {
	Key
}

type UpdatedPodIngressRuleBackend struct {
	Fields[UpdatedPodIngressRuleBackendFields]
	MetadbData[metadbmodel.PodIngressRuleBackend]
}
