// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodReplicaSets struct {
	MetadbItems[metadbmodel.PodReplicaSet]
	addition[AddNoneAddition]
}

type DeletedPodReplicaSets struct {
	Lcuuids
	MetadbItems[metadbmodel.PodReplicaSet]
	addition[DeleteNoneAddition]
}

type UpdatedPodReplicaSetFields struct {
	Key
	Name         fieldDetail[string]
	Label        fieldDetail[string]
	PodNum       fieldDetail[int]
	AzLcuuid     fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedPodReplicaSet struct {
	Fields[UpdatedPodReplicaSetFields]
	MetadbData[metadbmodel.PodReplicaSet]
}
