// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodGroups struct {
	MetadbItems[metadbmodel.PodGroup]
	addition[AddNoneAddition]
}

type DeletedPodGroups struct {
	Lcuuids
	MetadbItems[metadbmodel.PodGroup]
	addition[DeleteNoneAddition]
}

type UpdatedPodGroupFields struct {
	Key
	Name           fieldDetail[string]
	Label          fieldDetail[string]
	NetworkMode    fieldDetail[int]
	Type           fieldDetail[int]
	PodNum         fieldDetail[int]
	Metadata       fieldDetail[string]
	Spec           fieldDetail[string]
	AzLcuuid       fieldDetail[string]
	RegionLcuuid   fieldDetail[string]
	PodClusterId   fieldDetail[int]
	PodNamespaceId fieldDetail[int]
}

type UpdatedPodGroup struct {
	Fields[UpdatedPodGroupFields]
	MetadbData[metadbmodel.PodGroup]
}
