// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodIngressRules struct {
	MetadbItems[metadbmodel.PodIngressRule]
	addition[AddNoneAddition]
}

type DeletedPodIngressRules struct {
	Lcuuids
	MetadbItems[metadbmodel.PodIngressRule]
	addition[DeleteNoneAddition]
}

type UpdatedPodIngressRuleFields struct {
	Key
}

type UpdatedPodIngressRule struct {
	Fields[UpdatedPodIngressRuleFields]
	MetadbData[metadbmodel.PodIngressRule]
}
