// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodIngresses struct {
	MetadbItems[metadbmodel.PodIngress]
	addition[AddNoneAddition]
}

type DeletedPodIngresses struct {
	Lcuuids
	MetadbItems[metadbmodel.PodIngress]
	addition[DeleteNoneAddition]
}

type UpdatedPodIngressFields struct {
	Key
	Name         fieldDetail[string]
	AzLcuuid     fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedPodIngress struct {
	Fields[UpdatedPodIngressFields]
	MetadbData[metadbmodel.PodIngress]
}
