// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedPodClusters struct {
	MetadbItems[metadbmodel.PodCluster]
	addition[AddNoneAddition]
}

type DeletedPodClusters struct {
	Lcuuids
	MetadbItems[metadbmodel.PodCluster]
	addition[DeleteNoneAddition]
}

type UpdatedPodClusterFields struct {
	Key
	Name         fieldDetail[string]
	ClusterName  fieldDetail[string]
	AzLcuuid     fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedPodCluster struct {
	Fields[UpdatedPodClusterFields]
	MetadbData[metadbmodel.PodCluster]
}
