// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedProcesses struct {
	MetadbItems[metadbmodel.Process]
	addition[ProcessAddAddition]
}

type DeletedProcesses struct {
	Lcuuids
	MetadbItems[metadbmodel.Process]
	addition[ProcessDeleteAddition]
}

type UpdatedProcessFields struct {
	Key
	Name        fieldDetail[string]
	ProcessName fieldDetail[string]
	ContainerId fieldDetail[string]
	OsAppTags   fieldDetail[string]
	VmId        fieldDetail[int]
	VpcId       fieldDetail[int]
	Gid         fieldDetail[uint32]
}

type UpdatedProcess struct {
	Fields[UpdatedProcessFields]
	MetadbData[metadbmodel.Process]
}
