// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedRdsInstances struct {
	MetadbItems[metadbmodel.RDSInstance]
	addition[AddNoneAddition]
}

type DeletedRdsInstances struct {
	Lcuuids
	MetadbItems[metadbmodel.RDSInstance]
	addition[DeleteNoneAddition]
}

type UpdatedRdsInstanceFields struct {
	Key
	Name         fieldDetail[string]
	Uid          fieldDetail[string]
	State        fieldDetail[int]
	Series       fieldDetail[int]
	Model        fieldDetail[int]
	AzLcuuid     fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedRdsInstance struct {
	Fields[UpdatedRdsInstanceFields]
	MetadbData[metadbmodel.RDSInstance]
}
