// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedRedisInstances struct {
	MetadbItems[metadbmodel.RedisInstance]
	addition[AddNoneAddition]
}

type DeletedRedisInstances struct {
	Lcuuids
	MetadbItems[metadbmodel.RedisInstance]
	addition[DeleteNoneAddition]
}

type UpdatedRedisInstanceFields struct {
	Key
	Name         fieldDetail[string]
	Uid          fieldDetail[string]
	State        fieldDetail[int]
	PublicHost   fieldDetail[string]
	AzLcuuid     fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedRedisInstance struct {
	Fields[UpdatedRedisInstanceFields]
	MetadbData[metadbmodel.RedisInstance]
}
