// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedRegions struct {
	MetadbItems[metadbmodel.Region]
	addition[AddNoneAddition]
}

type DeletedRegions struct {
	Lcuuids
	MetadbItems[metadbmodel.Region]
	addition[DeleteNoneAddition]
}

type UpdatedRegionFields struct {
	Key
	Name  fieldDetail[string]
	Label fieldDetail[string]
}

type UpdatedRegion struct {
	Fields[UpdatedRegionFields]
	MetadbData[metadbmodel.Region]
}
