// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedRoutingTables struct {
	MetadbItems[metadbmodel.RoutingTable]
	addition[AddNoneAddition]
}

type DeletedRoutingTables struct {
	Lcuuids
	MetadbItems[metadbmodel.RoutingTable]
	addition[DeleteNoneAddition]
}

type UpdatedRoutingTableFields struct {
	Key
	Destination fieldDetail[string]
	NexthopType fieldDetail[string]
	Nexthop     fieldDetail[string]
}

type UpdatedRoutingTable struct {
	Fields[UpdatedRoutingTableFields]
	MetadbData[metadbmodel.RoutingTable]
}
