// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedSubDomains struct {
	MetadbItems[metadbmodel.SubDomain]
	addition[AddNoneAddition]
}

type DeletedSubDomains struct {
	Lcuuids
	MetadbItems[metadbmodel.SubDomain]
	addition[DeleteNoneAddition]
}

type UpdatedSubDomainFields struct {
	Key
	Name fieldDetail[string]
}

type UpdatedSubDomain struct {
	Fields[UpdatedSubDomainFields]
	MetadbData[metadbmodel.SubDomain]
}
