// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedSubnets struct {
	MetadbItems[metadbmodel.Subnet]
	addition[AddNoneAddition]
}

type DeletedSubnets struct {
	Lcuuids
	MetadbItems[metadbmodel.Subnet]
	addition[DeleteNoneAddition]
}

type UpdatedSubnetFields struct {
	Key
	Name  fieldDetail[string]
	Label fieldDetail[string]
}

type UpdatedSubnet struct {
	Fields[UpdatedSubnetFields]
	MetadbData[metadbmodel.Subnet]
}
