// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedVinterfaces struct {
	MetadbItems[metadbmodel.VInterface]
	addition[AddNoneAddition]
}

type DeletedVinterfaces struct {
	Lcuuids
	MetadbItems[metadbmodel.VInterface]
	addition[DeleteNoneAddition]
}

type UpdatedVinterfaceFields struct {
	Key
	Name          fieldDetail[string]
	TapMac        fieldDetail[string]
	Type          fieldDetail[int]
	NetnsId       fieldDetail[uint32]
	VtapId        fieldDetail[uint32]
	NetworkId     fieldDetail[int]
	NetworkLcuuid fieldDetail[string]
	RegionLcuuid  fieldDetail[string]
}

type UpdatedVinterface struct {
	Fields[UpdatedVinterfaceFields]
	MetadbData[metadbmodel.VInterface]
}
