// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedVips struct {
	MetadbItems[metadbmodel.VIP]
	addition[AddNoneAddition]
}

type DeletedVips struct {
	Lcuuids
	MetadbItems[metadbmodel.VIP]
	addition[DeleteNoneAddition]
}

type UpdatedVipFields struct {
	Key
	Ip     fieldDetail[string]
	VtapId fieldDetail[uint32]
}

type UpdatedVip struct {
	Fields[UpdatedVipFields]
	MetadbData[metadbmodel.VIP]
}
