// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedVms struct {
	MetadbItems[metadbmodel.VM]
	addition[AddNoneAddition]
}

type DeletedVms struct {
	Lcuuids
	MetadbItems[metadbmodel.VM]
	addition[DeleteNoneAddition]
}

type UpdatedVmFields struct {
	Key
	Name             fieldDetail[string]
	Ip               fieldDetail[string]
	Label            fieldDetail[string]
	State            fieldDetail[int]
	Htype            fieldDetail[int]
	LaunchServer     fieldDetail[string]
	LearnedCloudTags fieldDetail[map[string]string]
	CustomCloudTags  fieldDetail[map[string]string]
	HostId           fieldDetail[int]
	Uid              fieldDetail[string]
	Hostname         fieldDetail[string]
	VpcId            fieldDetail[int]
	VpcLcuuid        fieldDetail[string]
	AzLcuuid         fieldDetail[string]
	RegionLcuuid     fieldDetail[string]
	NetworkId        fieldDetail[int]
	NetworkLcuuid    fieldDetail[string]
}

type UpdatedVm struct {
	Fields[UpdatedVmFields]
	MetadbData[metadbmodel.VM]
}
