// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedVmPodNodeConnections struct {
	MetadbItems[metadbmodel.VMPodNodeConnection]
	addition[AddNoneAddition]
}

type DeletedVmPodNodeConnections struct {
	Lcuuids
	MetadbItems[metadbmodel.VMPodNodeConnection]
	addition[DeleteNoneAddition]
}

type UpdatedVmPodNodeConnectionFields struct {
	Key
}

type UpdatedVmPodNodeConnection struct {
	Fields[UpdatedVmPodNodeConnectionFields]
	MetadbData[metadbmodel.VMPodNodeConnection]
}
