// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedVpcs struct {
	MetadbItems[metadbmodel.VPC]
	addition[AddNoneAddition]
}

type DeletedVpcs struct {
	Lcuuids
	MetadbItems[metadbmodel.VPC]
	addition[DeleteNoneAddition]
}

type UpdatedVpcFields struct {
	Key
	Name         fieldDetail[string]
	Label        fieldDetail[string]
	Owner        fieldDetail[string]
	Cidr         fieldDetail[string]
	TunnelId     fieldDetail[int]
	RegionLcuuid fieldDetail[string]
	Uid          fieldDetail[string]
}

type UpdatedVpc struct {
	Fields[UpdatedVpcFields]
	MetadbData[metadbmodel.VPC]
}
