// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedVrouters struct {
	MetadbItems[metadbmodel.VRouter]
	addition[AddNoneAddition]
}

type DeletedVrouters struct {
	Lcuuids
	MetadbItems[metadbmodel.VRouter]
	addition[DeleteNoneAddition]
}

type UpdatedVrouterFields struct {
	Key
	Name         fieldDetail[string]
	Label        fieldDetail[string]
	VpcId        fieldDetail[int]
	VpcLcuuid    fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedVrouter struct {
	Fields[UpdatedVrouterFields]
	MetadbData[metadbmodel.VRouter]
}
