// Code generated by generator; DO NOT EDIT.

package message

import (
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

type AddedWanIps struct {
	MetadbItems[metadbmodel.WANIP]
	addition[AddNoneAddition]
}

type DeletedWanIps struct {
	Lcuuids
	MetadbItems[metadbmodel.WANIP]
	addition[DeleteNoneAddition]
}

type UpdatedWanIpFields struct {
	Key
	SubnetId     fieldDetail[int]
	SubnetLcuuid fieldDetail[string]
	RegionLcuuid fieldDetail[string]
}

type UpdatedWanIp struct {
	Fields[UpdatedWanIpFields]
	MetadbData[metadbmodel.WANIP]
}
