kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "deepflow-agent.fullname" . }}
  labels:
    {{- include "deepflow-agent.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.deepflowAgentConfig) $ | nindent 2 }}