FROM ubuntu:22.04

ARG TZ='Asia/Harbin'
ENV DEFAULT_TZ ${TZ}
ENV IN_CONTAINER yes
ENV RUST_BACKTRACE 1
ARG TARGETARCH
RUN --mount=target=/tmp-mount \
    chmod 600 /etc/passwd; \
    echo "deepflow:x:1000:1000::/home/deepflow:/bin/bash" >> /etc/passwd; \
    echo "root:root" | chpasswd; \
    chmod 000 /etc/passwd; \
    mkdir -p /lib64 && \
    apt-get update && apt-get upgrade -y && apt-get install \
    --no-install-suggests  --no-install-recommends -y \
    tzdata \
    iproute2 \
    bridge-utils \
    busybox && \
    /bin/cp /usr/share/zoneinfo/${DEFAULT_TZ} /etc/localtime && \
    AGENT_BUILD_ARCH=$(echo ${TARGETARCH}|sed 's|amd64|x86_64|'|sed 's|arm64|aarch64|') && \
    cp -raf /tmp-mount/${AGENT_BUILD_ARCH}/agent/output/target/release/deepflow-agent /bin/  && \
    cp -raf /tmp-mount/${AGENT_BUILD_ARCH}/agent/output/target/release/deepflow-agent-ctl /bin/  && \
    cp -raf /tmp-mount/${AGENT_BUILD_ARCH}/agent/output/src/ebpf/deepflow-ebpfctl /bin/  && \
    cp -raf /tmp-mount/agent/docker/require/${AGENT_BUILD_ARCH}/libpcap.so.1 /usr/lib/${AGENT_BUILD_ARCH}-linux-gnu/ && \
    chmod 777 /usr/lib/${AGENT_BUILD_ARCH}-linux-gnu/libpcap.so.1

USER root

CMD ["/bin/deepflow-agent", "-f", "/etc/deepflow-agent/deepflow-agent.yaml"]
