# TODO : aarch64 env rust-build update
FROM ghcr.io/deepflowio/rust-build:1.29-arm64 as builder
COPY .  /deepflow/
WORKDIR /deepflow/agent
ARG GITHUB_REF_NAME
RUN cargo build --release && \
    cargo build --release --bin deepflow-agent-ctl && \
    ls -alh target/release
FROM scratch
COPY --from=builder /deepflow/agent/ /
