FROM ghcr.io/deepflowio/rust-build:1.30 as builder
COPY .  /deepflow/
WORKDIR /deepflow/agent
ARG GITHUB_REF_NAME
RUN cp docker/rust-proxy-config /usr/local/cargo/config && \
    cargo build --release && \
    cargo build --release --bin deepflow-agent-ctl && \
    ls -alh target/release
FROM scratch
COPY --from=builder /deepflow/agent/ /
