FROM ghcr.io/deepflowio/rust-build:1.30

RUN rustup self uninstall -y
RUN curl https://sh.rustup.rs -so rustup.sh; bash rustup.sh -y
RUN sed -i -e 's/mirror.centos.org/vault.centos.org/g' \
           -e 's/^#.*baseurl=http/baseurl=http/g' \
           -e 's/^mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/*.repo

RUN yum install -y perl-IPC-Cmd perl-core which gcc-c++ wget unzip

WORKDIR /root
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/protoc-3.12.0-linux-x86_64.zip -O protoc-3.12.0.zip && unzip protoc-3.12.0.zip
RUN unzip protoc-3.12.0.zip -d protoc-3.12.0
RUN mv protoc-3.12.0/bin/* /usr/bin/ && cp -rf protoc-3.12.0/include/* /usr/include/
RUN yum clean all
