FROM docker.io/alpine

ARG TZ='Asia/Harbin'
ENV DEFAULT_TZ ${TZ}
ENV IN_CONTAINER yes
ENV RUST_BACKTRACE 1
ARG TARGETARCH
RUN --mount=target=/tmp-mount \
    apk upgrade --update \
    && apk add -U tzdata \
    && cp /usr/share/zoneinfo/${DEFAULT_TZ} /etc/localtime \
    && apk del tzdata \
    && rm -rf /var/cache/apk/*  && \
    chmod 600 /etc/passwd; \
    echo "deepflow:x:1000:1000::/home/deepflow:/bin/bash" >> /etc/passwd; \
    echo "root:root" | chpasswd; \
    chmod 000 /etc/passwd; \
    mkdir -p /lib64 && \
    AGENT_BUILD_ARCH=$(echo ${TARGETARCH}|sed 's|amd64|x86_64|'|sed 's|arm64|aarch64|') && \
    cp -raf /tmp-mount/${AGENT_BUILD_ARCH}/agent/output/target/${AGENT_BUILD_ARCH}-unknown-linux-musl/release/deepflow-agent /bin/  && \
    cp -raf /tmp-mount/${AGENT_BUILD_ARCH}/agent/output/target/${AGENT_BUILD_ARCH}-unknown-linux-musl/release/deepflow-agent-ctl /bin/  && \
    cp -raf /tmp-mount/${AGENT_BUILD_ARCH}/agent/output/src/ebpf/deepflow-ebpfctl /bin/  && \
    chmod 4755 /bin/busybox 

USER root

CMD /bin/deepflow-agent -f /etc/deepflow-agent/deepflow-agent.yaml
