FROM ghcr.io/deepflowio/rust-build:1.30-arm64

WORKDIR /root
RUN cp $CARGO_HOME/bin/sccache /root/sccache
RUN rustup self uninstall -y
RUN curl https://sh.rustup.rs -so rustup.sh; bash rustup.sh -y
RUN sed -i -e 's/mirror.centos.org/vault.centos.org/g' \
           -e 's/^#.*baseurl=http/baseurl=http/g' \
           -e 's/^mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/*.repo

RUN sed -i -e 's/vault.centos.org\/centos/vault.centos.org\/altarch/g' \
           -e 's/^#.*baseurl=http/baseurl=http/g' \
           -e 's/^mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/*.repo

RUN yum install -y perl-IPC-Cmd perl-core which gcc-c++ wget unzip

RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/protoc-3.12.0-linux-aarch_64.zip -O protoc-3.12.0.zip && unzip protoc-3.12.0.zip -d protoc-3.12.0
RUN mv protoc-3.12.0/bin/* /usr/bin/ && cp -rf protoc-3.12.0/include/* /usr/include/
RUN rm -rf protoc-3.12.0 && rm protoc-3.12.0.zip
RUN yum clean all

RUN rustup target add aarch64-unknown-linux-musl
# sccache latest version require openssl3, not satisfied
RUN mv /root/sccache $CARGO_HOME/bin/
