# TODO : aarch64 env rust-build update
FROM ghcr.io/deepflowio/rust-build:1.31-arm64 as builder
COPY .  /deepflow/
WORKDIR /deepflow/agent
ARG GITHUB_REF_NAME
RUN source /opt/rh/devtoolset-8/enable && \
    cargo build --release && \
    cargo build --release --bin deepflow-agent-ctl && \
    ls -alh target/release
FROM scratch
COPY --from=builder /deepflow/agent/ /
