FROM ghcr.io/deepflowys/rust-build:1.14 as builder
COPY .  /deepflow/
WORKDIR /deepflow/agent
RUN RUSTFLAGS="-D warnings" && cargo build --target=x86_64-unknown-linux-musl && \
    cargo build --release --bin deepflow-agent-ctl --target=x86_64-unknown-linux-musl && \
    ls -alh target/x86_64-unknown-linux-musl/release
FROM scratch
COPY --from=builder /deepflow/agent/ /
