FROM ghcr.io/deepflowys/rust-build:1.2 as builder
COPY .  /deepflow/
WORKDIR /deepflow/agent
RUN cargo build --release && \
    cargo build --release --bin deepflow-agent-ctl && \
    ls -alh target/release
FROM scratch
COPY --from=builder /deepflow/agent/ /


