FROM docker.io/alpine

ARG TZ='Asia/Harbin'
ENV DEFAULT_TZ ${TZ}
RUN apk upgrade --update \
    && apk add -U tzdata \
    && cp /usr/share/zoneinfo/${DEFAULT_TZ} /etc/localtime \
    && apk del tzdata \
    && rm -rf /var/cache/apk/*

COPY droplet /bin/
COPY droplet.yaml /etc/droplet/
RUN mkdir /lib64
COPY require /lib64
ENTRYPOINT /bin/droplet -f /etc/droplet/droplet.yaml
