// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// AZ defines cache data structure.
type AZ struct {
	lcuuid string
	id     int
	name   string
}

func (t *AZ) IsValid() bool {
	return t.lcuuid != ""
}

func (t *AZ) Lcuuid() string {
	return t.lcuuid
}

func (t *AZ) ID() int {
	return t.id
}

func (t *AZ) Name() string {
	return t.name
}

func (t *AZ) reset(dbItem *metadbmodel.AZ, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
}

func NewAZCollection(t *Tool) *AZCollection {
	c := new(AZCollection)
	c.collection = newCollectionBuilder[*AZ]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_AZ_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.AZ { return new(metadbmodel.AZ) }).
		withCacheItemFactory(func() *AZ { return new(AZ) }).
		build()
	return c
}

// AZCollection defines a collection that maps individual fields to the AZ cache data structure.
type AZCollection struct {
	collection[*AZ, *metadbmodel.AZ]
}
