// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Az defines cache data structure.
type Az struct {
	lcuuid string
	id     int
	name   string
}

func (t *Az) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Az) Lcuuid() string {
	return t.lcuuid
}

func (t *Az) Id() int {
	return t.id
}

func (t *Az) Name() string {
	return t.name
}

func (t *Az) reset(dbItem *metadbmodel.AZ, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
}

func NewAzCollection(t *Tool) *AzCollection {
	c := new(AzCollection)
	c.collection = newCollectionBuilder[*Az]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_AZ_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.AZ { return new(metadbmodel.AZ) }).
		withCacheItemFactory(func() *Az { return new(Az) }).
		build()
	return c
}

// AzCollection defines a collection that maps individual fields to the Az cache data structure.
type AzCollection struct {
	collection[*Az, *metadbmodel.AZ]
}
