// Code generated by generator; DO NOT EDIT.

package tool

import (
	mapset "github.com/deckarep/golang-set/v2"

	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// ConfigMap defines cache data structure.
type ConfigMap struct {
	lcuuid      string
	id          int
	name        string
	podGroupIDs mapset.Set[int] // data source: pod_group_config_map_connection
}

func (t *ConfigMap) IsValid() bool {
	return t.lcuuid != ""
}

func (t *ConfigMap) Lcuuid() string {
	return t.lcuuid
}

func (t *ConfigMap) ID() int {
	return t.id
}

func (t *ConfigMap) Name() string {
	return t.name
}

func (t *ConfigMap) PodGroupIDs() mapset.Set[int] {
	return t.podGroupIDs
}

func (t *ConfigMap) PodGroupIDsToSlice() []int {
	return t.podGroupIDs.ToSlice()
}

func (t *ConfigMap) AddPodGroupID(id int) {
	t.podGroupIDs.Add(id)
}

func (t *ConfigMap) RemovePodGroupID(id int) {
	t.podGroupIDs.Remove(id)
}

func (t *ConfigMap) reset(dbItem *metadbmodel.ConfigMap, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.podGroupIDs = mapset.NewSet[int]()
}

func NewConfigMapCollection(t *Tool) *ConfigMapCollection {
	c := new(ConfigMapCollection)
	c.collection = newCollectionBuilder[*ConfigMap]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_CONFIG_MAP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.ConfigMap { return new(metadbmodel.ConfigMap) }).
		withCacheItemFactory(func() *ConfigMap { return new(ConfigMap) }).
		build()
	return c
}

// ConfigMapCollection defines a collection that maps individual fields to the ConfigMap cache data structure.
type ConfigMapCollection struct {
	collection[*ConfigMap, *metadbmodel.ConfigMap]
}
