// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// DHCPPort defines cache data structure.
type DHCPPort struct {
	lcuuid   string
	id       int
	name     string
	regionID int
	azID     int
	vpcID    int
}

func (t *DHCPPort) IsValid() bool {
	return t.lcuuid != ""
}

func (t *DHCPPort) Lcuuid() string {
	return t.lcuuid
}

func (t *DHCPPort) ID() int {
	return t.id
}

func (t *DHCPPort) Name() string {
	return t.name
}

func (t *DHCPPort) Region() int {
	return t.regionID
}

func (t *DHCPPort) AZ() int {
	return t.azID
}

func (t *DHCPPort) VPCID() int {
	return t.vpcID
}

func (t *DHCPPort) reset(dbItem *metadbmodel.DHCPPort, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionID = tool.Region().GetByLcuuid(dbItem.Region).ID()
	t.azID = tool.AZ().GetByLcuuid(dbItem.AZ).ID()
	t.vpcID = dbItem.VPCID
}

func NewDHCPPortCollection(t *Tool) *DHCPPortCollection {
	c := new(DHCPPortCollection)
	c.collection = newCollectionBuilder[*DHCPPort]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_DHCP_PORT_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.DHCPPort { return new(metadbmodel.DHCPPort) }).
		withCacheItemFactory(func() *DHCPPort { return new(DHCPPort) }).
		build()
	return c
}

// DHCPPortCollection defines a collection that maps individual fields to the DHCPPort cache data structure.
type DHCPPortCollection struct {
	collection[*DHCPPort, *metadbmodel.DHCPPort]
}
