// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// DhcpPort defines cache data structure.
type DhcpPort struct {
	lcuuid   string
	id       int
	name     string
	regionId int
	azId     int
	vpcId    int
}

func (t *DhcpPort) IsValid() bool {
	return t.lcuuid != ""
}

func (t *DhcpPort) Lcuuid() string {
	return t.lcuuid
}

func (t *DhcpPort) Id() int {
	return t.id
}

func (t *DhcpPort) Name() string {
	return t.name
}

func (t *DhcpPort) RegionId() int {
	return t.regionId
}

func (t *DhcpPort) AzId() int {
	return t.azId
}

func (t *DhcpPort) VpcId() int {
	return t.vpcId
}

func (t *DhcpPort) reset(dbItem *metadbmodel.DHCPPort, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.vpcId = dbItem.VPCID
}

func NewDhcpPortCollection(t *Tool) *DhcpPortCollection {
	c := new(DhcpPortCollection)
	c.collection = newCollectionBuilder[*DhcpPort]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_DHCP_PORT_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.DHCPPort { return new(metadbmodel.DHCPPort) }).
		withCacheItemFactory(func() *DhcpPort { return new(DhcpPort) }).
		build()
	return c
}

// DhcpPortCollection defines a collection that maps individual fields to the DhcpPort cache data structure.
type DhcpPortCollection struct {
	collection[*DhcpPort, *metadbmodel.DHCPPort]
}
