// Code generated by generator; DO NOT EDIT.

package tool

import (
{{- if .HasMapset}}
	mapset "github.com/deckarep/golang-set/v2"
{{- end}}

	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// {{.PublicName}} defines cache data structure.
type {{.PublicName}} struct {
{{- range .Fields}}
{{- if not .IsExtension}}
{{- if .Comment}}
	{{.CamelName}} {{.Type}} // {{.Comment}}
{{- else}}
	{{.CamelName}} {{.Type}}
{{- end}}
{{- end}}
{{- end}}
{{- if .HasStructExtension}}
	{{.PublicName}}Ext
{{- end}}
}

func (t *{{.PublicName}}) IsValid() bool {
{{- range .Fields}}
{{- if .ForValidation}}
	return t.{{.CamelName}} != ""
{{- end}}
{{- end}}
}
{{range .Fields}}

func (t *{{$.PublicName}}) {{.PublicCamelName}}() {{.Type}} {
	return t.{{.CamelName}}
}
{{- end}}
{{- range .Fields}}
{{- if .ForMutation}}

func (t *{{$.PublicName}}) Set{{.PublicCamelName}}({{.CamelName}} {{.Type}}) {
	t.{{.CamelName}} = {{.CamelName}}
}
{{- end}}
{{- end}}
{{- range .Fields}}
{{- if .IsCollection}}

func (t *{{$.PublicName}}) {{.PublicCamelName}}ToSlice() []int {
	return t.{{.CamelName}}.ToSlice()
}

func (t *{{$.PublicName}}) AddPodGroupID(id int) {
	t.{{.CamelName}}.Add(id)
}

func (t *{{$.PublicName}}) RemovePodGroupID(id int) {
	t.{{.CamelName}}.Remove(id)
}
{{- end}}
{{- end}}

func (t *{{.PublicName}}) reset(dbItem *metadbmodel.{{.OrmName}}, tool *Tool) {
{{- range .Fields}}
{{- if and (not .ForMutation) (not .IsCollection) (not .IsExtension)}}
{{- if .Ref}}
	t.{{.CamelName}} = tool.{{.Ref.Resource}}().{{.Ref.LookupMethod}}(dbItem.{{.OrmName}}).{{.Ref.TargetField}}()
{{- else}}
	t.{{.CamelName}} = dbItem.{{.OrmName}}
{{- end}}
{{- end}}
{{- end}}
{{- if .HasStructExtension}}
	t.resetExt(dbItem, tool)
{{- end}}
{{- range .Fields}}
{{- if .IsCollection}}
	t.{{.CamelName}} = mapset.NewSet[int]()
{{- end}}
{{- end}}
}

func New{{.PublicName}}Collection(t *Tool) *{{.PublicName}}Collection {
	c := new({{.PublicName}}Collection)
{{- if .KeyFields}}
{{- range .KeyFields}}
	c.{{.CamelName}}ToItem = make(map[{{.Type}}]*{{$.PublicName}})
{{- end}}
{{- end}}
{{- if .CollectionExtension}}
	c.resetExt()
{{- end}}
	c.collection = newCollectionBuilder[*{{.PublicName}}]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_{{ToUpper .Name}}_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.{{.OrmName}} { return new(metadbmodel.{{.OrmName}}) }).
		withCacheItemFactory(func() *{{.PublicName}} { return new({{.PublicName}}) }).
{{- if or .KeyFields .CollectionExtension}}
		withExtender(c).
{{- end}}
		build()
	return c
}

// {{.PublicName}}Collection defines a collection that maps individual fields to the {{.PublicName}} cache data structure.
type {{.PublicName}}Collection struct {
	collection[*{{.PublicName}}, *metadbmodel.{{.OrmName}}]
{{- if .KeyFields}}
{{- range .KeyFields}}
	{{.CamelName}}ToItem map[{{.Type}}]*{{$.PublicName}}
{{- end}}
{{- end}}
{{- if .CollectionExtension}}
	{{.PublicName}}CollectionExt
{{- end}}
}

{{- if .KeyFields}}

// OnAfterAdd implements CollectionExtender interface
func (c *{{.PublicName}}Collection) OnAfterAdd(item *{{.PublicName}}, dbItem *metadbmodel.{{.OrmName}}) {
{{- range .KeyFields}}
	if item.{{.PublicCamelName}}() != "" {
		c.{{.CamelName}}ToItem[item.{{.PublicCamelName}}()] = item
	}
{{- end}}
}

// OnAfterUpdate implements CollectionExtender interface  
func (c *{{.PublicName}}Collection) OnAfterUpdate(item *{{.PublicName}}, dbItem *metadbmodel.{{.OrmName}}) {
{{- range .KeyFields}}
	// Remove old {{.Name}} mapping if exists
	for {{.CamelName}}, {{$.PublicName | toLowerCamel}}Item := range c.{{.CamelName}}ToItem {
		if {{$.PublicName | toLowerCamel}}Item == item && {{.CamelName}} != item.{{.PublicCamelName}}() {
			delete(c.{{.CamelName}}ToItem, {{.CamelName}})
			break
		}
	}
	// Add new {{.Name}} mapping
	if item.{{.PublicCamelName}}() != "" {
		c.{{.CamelName}}ToItem[item.{{.PublicCamelName}}()] = item
	}
{{- end}}
}

// OnAfterDelete implements CollectionExtender interface
func (c *{{.PublicName}}Collection) OnAfterDelete(item *{{.PublicName}}, dbItem *metadbmodel.{{.OrmName}}) {
{{- range .KeyFields}}
	if item.{{.PublicCamelName}}() != "" {
		delete(c.{{.CamelName}}ToItem, item.{{.PublicCamelName}}())
	}
{{- end}}
}

{{- range .KeyFields}}
// GetOrLoadBy{{.PublicCamelName}} returns the {{$.PublicName}} by its {{.CamelName}}, loading from DB if not found in cache.
func (c *{{$.PublicName}}Collection) GetOrLoadBy{{.PublicCamelName}}({{.CamelName}} {{.Type}}) *{{$.PublicName}} {
	{{if eq .Type "string"}}
	if {{.CamelName}} == "" {
		return new({{$.PublicName}})
	}
	{{else if eq .Type "int"}}
	if {{.CamelName}} == 0 {
		return new({{$.PublicName}})
	}
	{{end}}

	item, ok := c.{{.CamelName}}ToItem[{{.CamelName}}]
	if ok {
		return item
	}
	log.Warning("cache %s ({{.CamelName}}: %v) not found", c.resourceType, {{.CamelName}})

	var dbItem *metadbmodel.{{$.OrmName}}
	if result := c.tool.metadata.GetDB().Where("{{.Name}} = ?", {{.CamelName}}).First(&dbItem); result.RowsAffected == 1 {
		c.Add(dbItem)
		return c.{{.CamelName}}ToItem[{{.CamelName}}]
	} else {
		log.Error("db %s ({{.CamelName}}: %v) not found", c.resourceType, {{.CamelName}})
		return new({{$.PublicName}})
	}
}

// GetBy{{.PublicCamelName}} returns the {{$.PublicName}} by its {{.CamelName}} directly from cache.
func (c *{{$.PublicName}}Collection) GetBy{{.PublicCamelName}}({{.CamelName}} {{.Type}}) *{{$.PublicName}} {
	{{if eq .Type "string"}}
	if {{.CamelName}} == "" {
		return new({{$.PublicName}})
	}
	{{else if eq .Type "int"}}
	if {{.CamelName}} == 0 {
		return new({{$.PublicName}})
	}
	{{end}}

	item, ok := c.{{.CamelName}}ToItem[{{.CamelName}}]
	if ok {
		return item
	}
	log.Warning("cache %s ({{.CamelName}}: %v) not found", c.resourceType, {{.CamelName}})
	return new({{$.PublicName}})
}
{{- end}}
{{- end}}
