// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// LanIp defines cache data structure.
type LanIp struct {
	lcuuid       string
	id           int
	ip           string
	vinterfaceId int
}

func (t *LanIp) IsValid() bool {
	return t.lcuuid != ""
}

func (t *LanIp) Lcuuid() string {
	return t.lcuuid
}

func (t *LanIp) Id() int {
	return t.id
}

func (t *LanIp) Ip() string {
	return t.ip
}

func (t *LanIp) VinterfaceId() int {
	return t.vinterfaceId
}

func (t *LanIp) reset(dbItem *metadbmodel.LANIP, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.ip = dbItem.IP
	t.vinterfaceId = dbItem.VInterfaceID
}

func NewLanIpCollection(t *Tool) *LanIpCollection {
	c := new(LanIpCollection)
	c.resetExt()
	c.collection = newCollectionBuilder[*LanIp]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LAN_IP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LANIP { return new(metadbmodel.LANIP) }).
		withCacheItemFactory(func() *LanIp { return new(LanIp) }).
		withExtender(c).
		build()
	return c
}

// LanIpCollection defines a collection that maps individual fields to the LanIp cache data structure.
type LanIpCollection struct {
	collection[*LanIp, *metadbmodel.LANIP]
	LanIpCollectionExt
}
