// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Lb defines cache data structure.
type Lb struct {
	lcuuid   string
	id       int
	name     string
	regionId int
	vpcId    int
}

func (t *Lb) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Lb) Lcuuid() string {
	return t.lcuuid
}

func (t *Lb) Id() int {
	return t.id
}

func (t *Lb) Name() string {
	return t.name
}

func (t *Lb) RegionId() int {
	return t.regionId
}

func (t *Lb) VpcId() int {
	return t.vpcId
}

func (t *Lb) reset(dbItem *metadbmodel.LB, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.vpcId = dbItem.VPCID
}

func NewLbCollection(t *Tool) *LbCollection {
	c := new(LbCollection)
	c.collection = newCollectionBuilder[*Lb]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LB_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LB { return new(metadbmodel.LB) }).
		withCacheItemFactory(func() *Lb { return new(Lb) }).
		build()
	return c
}

// LbCollection defines a collection that maps individual fields to the Lb cache data structure.
type LbCollection struct {
	collection[*Lb, *metadbmodel.LB]
}
