// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// LB defines cache data structure.
type LB struct {
	lcuuid   string
	id       int
	name     string
	regionID int
	vpcID    int
}

func (t *LB) IsValid() bool {
	return t.lcuuid != ""
}

func (t *LB) Lcuuid() string {
	return t.lcuuid
}

func (t *LB) ID() int {
	return t.id
}

func (t *LB) Name() string {
	return t.name
}

func (t *LB) RegionID() int {
	return t.regionID
}

func (t *LB) VPCID() int {
	return t.vpcID
}

func (t *LB) reset(dbItem *metadbmodel.LB, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionID = tool.Region().GetByLcuuid(dbItem.Region).ID()
	t.vpcID = dbItem.VPCID
}

func NewLBCollection(t *Tool) *LBCollection {
	c := new(LBCollection)
	c.collection = newCollectionBuilder[*LB]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LB_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LB { return new(metadbmodel.LB) }).
		withCacheItemFactory(func() *LB { return new(LB) }).
		build()
	return c
}

// LBCollection defines a collection that maps individual fields to the LB cache data structure.
type LBCollection struct {
	collection[*LB, *metadbmodel.LB]
}
