// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// LBListener defines cache data structure.
type LBListener struct {
	lcuuid string
	id     int
	name   string
	lbID   int
}

func (t *LBListener) IsValid() bool {
	return t.lcuuid != ""
}

func (t *LBListener) Lcuuid() string {
	return t.lcuuid
}

func (t *LBListener) ID() int {
	return t.id
}

func (t *LBListener) Name() string {
	return t.name
}

func (t *LBListener) LBID() int {
	return t.lbID
}

func (t *LBListener) reset(dbItem *metadbmodel.LBListener, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.lbID = dbItem.LBID
}

func NewLBListenerCollection(t *Tool) *LBListenerCollection {
	c := new(LBListenerCollection)
	c.collection = newCollectionBuilder[*LBListener]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LB_LISTENER_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LBListener { return new(metadbmodel.LBListener) }).
		withCacheItemFactory(func() *LBListener { return new(LBListener) }).
		build()
	return c
}

// LBListenerCollection defines a collection that maps individual fields to the LBListener cache data structure.
type LBListenerCollection struct {
	collection[*LBListener, *metadbmodel.LBListener]
}
