// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// LbListener defines cache data structure.
type LbListener struct {
	lcuuid string
	id     int
	name   string
	lbId   int
}

func (t *LbListener) IsValid() bool {
	return t.lcuuid != ""
}

func (t *LbListener) Lcuuid() string {
	return t.lcuuid
}

func (t *LbListener) Id() int {
	return t.id
}

func (t *LbListener) Name() string {
	return t.name
}

func (t *LbListener) LbId() int {
	return t.lbId
}

func (t *LbListener) reset(dbItem *metadbmodel.LBListener, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.lbId = dbItem.LBID
}

func NewLbListenerCollection(t *Tool) *LbListenerCollection {
	c := new(LbListenerCollection)
	c.collection = newCollectionBuilder[*LbListener]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_LB_LISTENER_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.LBListener { return new(metadbmodel.LBListener) }).
		withCacheItemFactory(func() *LbListener { return new(LbListener) }).
		build()
	return c
}

// LbListenerCollection defines a collection that maps individual fields to the LbListener cache data structure.
type LbListenerCollection struct {
	collection[*LbListener, *metadbmodel.LBListener]
}
