// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// NatGateway defines cache data structure.
type NatGateway struct {
	lcuuid   string
	id       int
	name     string
	regionId int
	azId     int
	vpcId    int
}

func (t *NatGateway) IsValid() bool {
	return t.lcuuid != ""
}

func (t *NatGateway) Lcuuid() string {
	return t.lcuuid
}

func (t *NatGateway) Id() int {
	return t.id
}

func (t *NatGateway) Name() string {
	return t.name
}

func (t *NatGateway) RegionId() int {
	return t.regionId
}

func (t *NatGateway) AzId() int {
	return t.azId
}

func (t *NatGateway) VpcId() int {
	return t.vpcId
}

func (t *NatGateway) reset(dbItem *metadbmodel.NATGateway, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.vpcId = dbItem.VPCID
}

func NewNatGatewayCollection(t *Tool) *NatGatewayCollection {
	c := new(NatGatewayCollection)
	c.collection = newCollectionBuilder[*NatGateway]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_NAT_GATEWAY_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.NATGateway { return new(metadbmodel.NATGateway) }).
		withCacheItemFactory(func() *NatGateway { return new(NatGateway) }).
		build()
	return c
}

// NatGatewayCollection defines a collection that maps individual fields to the NatGateway cache data structure.
type NatGatewayCollection struct {
	collection[*NatGateway, *metadbmodel.NATGateway]
}
