// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// NATGateway defines cache data structure.
type NATGateway struct {
	lcuuid   string
	id       int
	name     string
	regionID int
	azID     int
	vpcID    int
}

func (t *NATGateway) IsValid() bool {
	return t.lcuuid != ""
}

func (t *NATGateway) Lcuuid() string {
	return t.lcuuid
}

func (t *NATGateway) ID() int {
	return t.id
}

func (t *NATGateway) Name() string {
	return t.name
}

func (t *NATGateway) RegionID() int {
	return t.regionID
}

func (t *NATGateway) AZID() int {
	return t.azID
}

func (t *NATGateway) VPCID() int {
	return t.vpcID
}

func (t *NATGateway) reset(dbItem *metadbmodel.NATGateway, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionID = tool.Region().GetByLcuuid(dbItem.Region).ID()
	t.azID = tool.AZ().GetByLcuuid(dbItem.AZ).ID()
	t.vpcID = dbItem.VPCID
}

func NewNATGatewayCollection(t *Tool) *NATGatewayCollection {
	c := new(NATGatewayCollection)
	c.collection = newCollectionBuilder[*NATGateway]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_NAT_GATEWAY_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.NATGateway { return new(metadbmodel.NATGateway) }).
		withCacheItemFactory(func() *NATGateway { return new(NATGateway) }).
		build()
	return c
}

// NATGatewayCollection defines a collection that maps individual fields to the NATGateway cache data structure.
type NATGatewayCollection struct {
	collection[*NATGateway, *metadbmodel.NATGateway]
}
