// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Network defines cache data structure.
type Network struct {
	lcuuid string
	id     int
	name   string
	vpcId  int
}

func (t *Network) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Network) Lcuuid() string {
	return t.lcuuid
}

func (t *Network) Id() int {
	return t.id
}

func (t *Network) Name() string {
	return t.name
}

func (t *Network) VpcId() int {
	return t.vpcId
}

func (t *Network) reset(dbItem *metadbmodel.Network, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.vpcId = dbItem.VPCID
}

func NewNetworkCollection(t *Tool) *NetworkCollection {
	c := new(NetworkCollection)
	c.collection = newCollectionBuilder[*Network]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_NETWORK_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Network { return new(metadbmodel.Network) }).
		withCacheItemFactory(func() *Network { return new(Network) }).
		build()
	return c
}

// NetworkCollection defines a collection that maps individual fields to the Network cache data structure.
type NetworkCollection struct {
	collection[*Network, *metadbmodel.Network]
}
