// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Pod defines cache data structure.
type Pod struct {
	lcuuid         string
	id             int
	domainLcuuid   string
	name           string
	regionId       int
	azId           int
	vpcId          int
	podClusterId   int
	podNamespaceId int
	podGroupId     int
	podNodeId      int
}

func (t *Pod) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Pod) Lcuuid() string {
	return t.lcuuid
}

func (t *Pod) Id() int {
	return t.id
}

func (t *Pod) DomainLcuuid() string {
	return t.domainLcuuid
}

func (t *Pod) Name() string {
	return t.name
}

func (t *Pod) RegionId() int {
	return t.regionId
}

func (t *Pod) AzId() int {
	return t.azId
}

func (t *Pod) VpcId() int {
	return t.vpcId
}

func (t *Pod) PodClusterId() int {
	return t.podClusterId
}

func (t *Pod) PodNamespaceId() int {
	return t.podNamespaceId
}

func (t *Pod) PodGroupId() int {
	return t.podGroupId
}

func (t *Pod) PodNodeId() int {
	return t.podNodeId
}

func (t *Pod) reset(dbItem *metadbmodel.Pod, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.domainLcuuid = dbItem.Domain
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.vpcId = dbItem.VPCID
	t.podClusterId = dbItem.PodClusterID
	t.podNamespaceId = dbItem.PodNamespaceID
	t.podGroupId = dbItem.PodGroupID
	t.podNodeId = dbItem.PodNodeID
}

func NewPodCollection(t *Tool) *PodCollection {
	c := new(PodCollection)
	c.resetExt()
	c.collection = newCollectionBuilder[*Pod]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Pod { return new(metadbmodel.Pod) }).
		withCacheItemFactory(func() *Pod { return new(Pod) }).
		withExtender(c).
		build()
	return c
}

// PodCollection defines a collection that maps individual fields to the Pod cache data structure.
type PodCollection struct {
	collection[*Pod, *metadbmodel.Pod]
	PodCollectionExt
}
