// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodIngressRule defines cache data structure.
type PodIngressRule struct {
	lcuuid string
	id     int
	name   string
}

func (t *PodIngressRule) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodIngressRule) Lcuuid() string {
	return t.lcuuid
}

func (t *PodIngressRule) ID() int {
	return t.id
}

func (t *PodIngressRule) Name() string {
	return t.name
}

func (t *PodIngressRule) reset(dbItem *metadbmodel.PodIngressRule, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
}

func NewPodIngressRuleCollection(t *Tool) *PodIngressRuleCollection {
	c := new(PodIngressRuleCollection)
	c.collection = newCollectionBuilder[*PodIngressRule]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_INGRESS_RULE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodIngressRule { return new(metadbmodel.PodIngressRule) }).
		withCacheItemFactory(func() *PodIngressRule { return new(PodIngressRule) }).
		build()
	return c
}

// PodIngressRuleCollection defines a collection that maps individual fields to the PodIngressRule cache data structure.
type PodIngressRuleCollection struct {
	collection[*PodIngressRule, *metadbmodel.PodIngressRule]
}
