// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodCluster defines cache data structure.
type PodCluster struct {
	lcuuid   string
	id       int
	name     string
	regionId int
	azId     int
	vpcId    int
}

func (t *PodCluster) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodCluster) Lcuuid() string {
	return t.lcuuid
}

func (t *PodCluster) Id() int {
	return t.id
}

func (t *PodCluster) Name() string {
	return t.name
}

func (t *PodCluster) RegionId() int {
	return t.regionId
}

func (t *PodCluster) AzId() int {
	return t.azId
}

func (t *PodCluster) VpcId() int {
	return t.vpcId
}

func (t *PodCluster) reset(dbItem *metadbmodel.PodCluster, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.vpcId = dbItem.VPCID
}

func NewPodClusterCollection(t *Tool) *PodClusterCollection {
	c := new(PodClusterCollection)
	c.collection = newCollectionBuilder[*PodCluster]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_CLUSTER_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodCluster { return new(metadbmodel.PodCluster) }).
		withCacheItemFactory(func() *PodCluster { return new(PodCluster) }).
		build()
	return c
}

// PodClusterCollection defines a collection that maps individual fields to the PodCluster cache data structure.
type PodClusterCollection struct {
	collection[*PodCluster, *metadbmodel.PodCluster]
}
