// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodCluster defines cache data structure.
type PodCluster struct {
	lcuuid   string
	id       int
	name     string
	regionID int
	azID     int
	vpcID    int
}

func (t *PodCluster) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodCluster) Lcuuid() string {
	return t.lcuuid
}

func (t *PodCluster) ID() int {
	return t.id
}

func (t *PodCluster) Name() string {
	return t.name
}

func (t *PodCluster) RegionID() int {
	return t.regionID
}

func (t *PodCluster) AZID() int {
	return t.azID
}

func (t *PodCluster) VPCID() int {
	return t.vpcID
}

func (t *PodCluster) reset(dbItem *metadbmodel.PodCluster, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionID = tool.Region().GetByLcuuid(dbItem.Region).ID()
	t.azID = tool.AZ().GetByLcuuid(dbItem.AZ).ID()
	t.vpcID = dbItem.VPCID
}

func NewPodClusterCollection(t *Tool) *PodClusterCollection {
	c := new(PodClusterCollection)
	c.collection = newCollectionBuilder[*PodCluster]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_CLUSTER_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodCluster { return new(metadbmodel.PodCluster) }).
		withCacheItemFactory(func() *PodCluster { return new(PodCluster) }).
		build()
	return c
}

// PodClusterCollection defines a collection that maps individual fields to the PodCluster cache data structure.
type PodClusterCollection struct {
	collection[*PodCluster, *metadbmodel.PodCluster]
}
