// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodReplicaSet defines cache data structure.
type PodReplicaSet struct {
	lcuuid         string
	id             int
	name           string
	regionId       int
	azId           int
	podGroupId     int
	podNamespaceId int
	podClusterId   int
}

func (t *PodReplicaSet) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodReplicaSet) Lcuuid() string {
	return t.lcuuid
}

func (t *PodReplicaSet) Id() int {
	return t.id
}

func (t *PodReplicaSet) Name() string {
	return t.name
}

func (t *PodReplicaSet) RegionId() int {
	return t.regionId
}

func (t *PodReplicaSet) AzId() int {
	return t.azId
}

func (t *PodReplicaSet) PodGroupId() int {
	return t.podGroupId
}

func (t *PodReplicaSet) PodNamespaceId() int {
	return t.podNamespaceId
}

func (t *PodReplicaSet) PodClusterId() int {
	return t.podClusterId
}

func (t *PodReplicaSet) reset(dbItem *metadbmodel.PodReplicaSet, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.podGroupId = dbItem.PodGroupID
	t.podNamespaceId = dbItem.PodNamespaceID
	t.podClusterId = dbItem.PodClusterID
}

func NewPodReplicaSetCollection(t *Tool) *PodReplicaSetCollection {
	c := new(PodReplicaSetCollection)
	c.collection = newCollectionBuilder[*PodReplicaSet]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_REPLICA_SET_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodReplicaSet { return new(metadbmodel.PodReplicaSet) }).
		withCacheItemFactory(func() *PodReplicaSet { return new(PodReplicaSet) }).
		build()
	return c
}

// PodReplicaSetCollection defines a collection that maps individual fields to the PodReplicaSet cache data structure.
type PodReplicaSetCollection struct {
	collection[*PodReplicaSet, *metadbmodel.PodReplicaSet]
}
