// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodIngress defines cache data structure.
type PodIngress struct {
	lcuuid         string
	id             int
	name           string
	regionId       int
	azId           int
	podNamespaceId int
	podClusterId   int
}

func (t *PodIngress) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodIngress) Lcuuid() string {
	return t.lcuuid
}

func (t *PodIngress) Id() int {
	return t.id
}

func (t *PodIngress) Name() string {
	return t.name
}

func (t *PodIngress) RegionId() int {
	return t.regionId
}

func (t *PodIngress) AzId() int {
	return t.azId
}

func (t *PodIngress) PodNamespaceId() int {
	return t.podNamespaceId
}

func (t *PodIngress) PodClusterId() int {
	return t.podClusterId
}

func (t *PodIngress) reset(dbItem *metadbmodel.PodIngress, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.podNamespaceId = dbItem.PodNamespaceID
	t.podClusterId = dbItem.PodClusterID
}

func NewPodIngressCollection(t *Tool) *PodIngressCollection {
	c := new(PodIngressCollection)
	c.collection = newCollectionBuilder[*PodIngress]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_INGRESS_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodIngress { return new(metadbmodel.PodIngress) }).
		withCacheItemFactory(func() *PodIngress { return new(PodIngress) }).
		build()
	return c
}

// PodIngressCollection defines a collection that maps individual fields to the PodIngress cache data structure.
type PodIngressCollection struct {
	collection[*PodIngress, *metadbmodel.PodIngress]
}
