// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodGroup defines cache data structure.
type PodGroup struct {
	lcuuid         string
	id             int
	name           string
	gType          int
	regionId       int
	azId           int
	podNamespaceId int
	podClusterId   int
}

func (t *PodGroup) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodGroup) Lcuuid() string {
	return t.lcuuid
}

func (t *PodGroup) Id() int {
	return t.id
}

func (t *PodGroup) Name() string {
	return t.name
}

func (t *PodGroup) GType() int {
	return t.gType
}

func (t *PodGroup) RegionId() int {
	return t.regionId
}

func (t *PodGroup) AzId() int {
	return t.azId
}

func (t *PodGroup) PodNamespaceId() int {
	return t.podNamespaceId
}

func (t *PodGroup) PodClusterId() int {
	return t.podClusterId
}

func (t *PodGroup) reset(dbItem *metadbmodel.PodGroup, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.gType = dbItem.Type
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.podNamespaceId = dbItem.PodNamespaceID
	t.podClusterId = dbItem.PodClusterID
}

func NewPodGroupCollection(t *Tool) *PodGroupCollection {
	c := new(PodGroupCollection)
	c.collection = newCollectionBuilder[*PodGroup]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_GROUP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodGroup { return new(metadbmodel.PodGroup) }).
		withCacheItemFactory(func() *PodGroup { return new(PodGroup) }).
		build()
	return c
}

// PodGroupCollection defines a collection that maps individual fields to the PodGroup cache data structure.
type PodGroupCollection struct {
	collection[*PodGroup, *metadbmodel.PodGroup]
}
