// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodNamespace defines cache data structure.
type PodNamespace struct {
	lcuuid       string
	id           int
	name         string
	regionId     int
	azId         int
	podClusterId int
}

func (t *PodNamespace) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodNamespace) Lcuuid() string {
	return t.lcuuid
}

func (t *PodNamespace) Id() int {
	return t.id
}

func (t *PodNamespace) Name() string {
	return t.name
}

func (t *PodNamespace) RegionId() int {
	return t.regionId
}

func (t *PodNamespace) AzId() int {
	return t.azId
}

func (t *PodNamespace) PodClusterId() int {
	return t.podClusterId
}

func (t *PodNamespace) reset(dbItem *metadbmodel.PodNamespace, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.podClusterId = dbItem.PodClusterID
}

func NewPodNamespaceCollection(t *Tool) *PodNamespaceCollection {
	c := new(PodNamespaceCollection)
	c.collection = newCollectionBuilder[*PodNamespace]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_NAMESPACE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodNamespace { return new(metadbmodel.PodNamespace) }).
		withCacheItemFactory(func() *PodNamespace { return new(PodNamespace) }).
		build()
	return c
}

// PodNamespaceCollection defines a collection that maps individual fields to the PodNamespace cache data structure.
type PodNamespaceCollection struct {
	collection[*PodNamespace, *metadbmodel.PodNamespace]
}
