// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodService defines cache data structure.
type PodService struct {
	lcuuid         string
	id             int
	name           string
	regionId       int
	azId           int
	vpcId          int
	podClusterId   int
	podNamespaceId int
}

func (t *PodService) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodService) Lcuuid() string {
	return t.lcuuid
}

func (t *PodService) Id() int {
	return t.id
}

func (t *PodService) Name() string {
	return t.name
}

func (t *PodService) RegionId() int {
	return t.regionId
}

func (t *PodService) AzId() int {
	return t.azId
}

func (t *PodService) VpcId() int {
	return t.vpcId
}

func (t *PodService) PodClusterId() int {
	return t.podClusterId
}

func (t *PodService) PodNamespaceId() int {
	return t.podNamespaceId
}

func (t *PodService) reset(dbItem *metadbmodel.PodService, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.vpcId = dbItem.VPCID
	t.podClusterId = dbItem.PodClusterID
	t.podNamespaceId = dbItem.PodNamespaceID
}

func NewPodServiceCollection(t *Tool) *PodServiceCollection {
	c := new(PodServiceCollection)
	c.collection = newCollectionBuilder[*PodService]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_SERVICE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodService { return new(metadbmodel.PodService) }).
		withCacheItemFactory(func() *PodService { return new(PodService) }).
		build()
	return c
}

// PodServiceCollection defines a collection that maps individual fields to the PodService cache data structure.
type PodServiceCollection struct {
	collection[*PodService, *metadbmodel.PodService]
}
