// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodNode defines cache data structure.
type PodNode struct {
	lcuuid       string
	id           int
	domainLcuuid string
	name         string
	regionId     int
	azId         int
	vpcId        int
	podClusterId int
	vmId         int
}

func (t *PodNode) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodNode) Lcuuid() string {
	return t.lcuuid
}

func (t *PodNode) Id() int {
	return t.id
}

func (t *PodNode) DomainLcuuid() string {
	return t.domainLcuuid
}

func (t *PodNode) Name() string {
	return t.name
}

func (t *PodNode) RegionId() int {
	return t.regionId
}

func (t *PodNode) AzId() int {
	return t.azId
}

func (t *PodNode) VpcId() int {
	return t.vpcId
}

func (t *PodNode) PodClusterId() int {
	return t.podClusterId
}

func (t *PodNode) VmId() int {
	return t.vmId
}

func (t *PodNode) SetVmId(vmId int) {
	t.vmId = vmId
}

func (t *PodNode) reset(dbItem *metadbmodel.PodNode, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.domainLcuuid = dbItem.Domain
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.vpcId = dbItem.VPCID
	t.podClusterId = dbItem.PodClusterID
}

func NewPodNodeCollection(t *Tool) *PodNodeCollection {
	c := new(PodNodeCollection)
	c.collection = newCollectionBuilder[*PodNode]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_NODE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodNode { return new(metadbmodel.PodNode) }).
		withCacheItemFactory(func() *PodNode { return new(PodNode) }).
		build()
	return c
}

// PodNodeCollection defines a collection that maps individual fields to the PodNode cache data structure.
type PodNodeCollection struct {
	collection[*PodNode, *metadbmodel.PodNode]
}
