// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// PodGroupConfigMapConnection defines cache data structure.
type PodGroupConfigMapConnection struct {
	lcuuid      string
	id          int
	configMapId int
	podGroupId  int
}

func (t *PodGroupConfigMapConnection) IsValid() bool {
	return t.lcuuid != ""
}

func (t *PodGroupConfigMapConnection) Lcuuid() string {
	return t.lcuuid
}

func (t *PodGroupConfigMapConnection) Id() int {
	return t.id
}

func (t *PodGroupConfigMapConnection) ConfigMapId() int {
	return t.configMapId
}

func (t *PodGroupConfigMapConnection) PodGroupId() int {
	return t.podGroupId
}

func (t *PodGroupConfigMapConnection) reset(dbItem *metadbmodel.PodGroupConfigMapConnection, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.configMapId = dbItem.ConfigMapID
	t.podGroupId = dbItem.PodGroupID
}

func NewPodGroupConfigMapConnectionCollection(t *Tool) *PodGroupConfigMapConnectionCollection {
	c := new(PodGroupConfigMapConnectionCollection)
	c.collection = newCollectionBuilder[*PodGroupConfigMapConnection]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_POD_GROUP_CONFIG_MAP_CONNECTION_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.PodGroupConfigMapConnection { return new(metadbmodel.PodGroupConfigMapConnection) }).
		withCacheItemFactory(func() *PodGroupConfigMapConnection { return new(PodGroupConfigMapConnection) }).
		build()
	return c
}

// PodGroupConfigMapConnectionCollection defines a collection that maps individual fields to the PodGroupConfigMapConnection cache data structure.
type PodGroupConfigMapConnectionCollection struct {
	collection[*PodGroupConfigMapConnection, *metadbmodel.PodGroupConfigMapConnection]
}
