// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Process defines cache data structure.
type Process struct {
	lcuuid     string
	id         int
	name       string
	deviceType int
	deviceId   int
	podGroupId int
	podNodeId  int
	vmId       int
	vpcId      int
}

func (t *Process) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Process) Lcuuid() string {
	return t.lcuuid
}

func (t *Process) Id() int {
	return t.id
}

func (t *Process) Name() string {
	return t.name
}

func (t *Process) DeviceType() int {
	return t.deviceType
}

func (t *Process) DeviceId() int {
	return t.deviceId
}

func (t *Process) PodGroupId() int {
	return t.podGroupId
}

func (t *Process) PodNodeId() int {
	return t.podNodeId
}

func (t *Process) VmId() int {
	return t.vmId
}

func (t *Process) VpcId() int {
	return t.vpcId
}

func (t *Process) reset(dbItem *metadbmodel.Process, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.deviceType = dbItem.DeviceType
	t.deviceId = dbItem.DeviceID
	t.podGroupId = dbItem.PodGroupID
	t.podNodeId = dbItem.PodNodeID
	t.vmId = dbItem.VMID
	t.vpcId = dbItem.VPCID
}

func NewProcessCollection(t *Tool) *ProcessCollection {
	c := new(ProcessCollection)
	c.resetExt()
	c.collection = newCollectionBuilder[*Process]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_PROCESS_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Process { return new(metadbmodel.Process) }).
		withCacheItemFactory(func() *Process { return new(Process) }).
		withExtender(c).
		build()
	return c
}

// ProcessCollection defines a collection that maps individual fields to the Process cache data structure.
type ProcessCollection struct {
	collection[*Process, *metadbmodel.Process]
	ProcessCollectionExt
}
