// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// RdsInstance defines cache data structure.
type RdsInstance struct {
	lcuuid   string
	id       int
	name     string
	regionId int
	azId     int
	vpcId    int
}

func (t *RdsInstance) IsValid() bool {
	return t.lcuuid != ""
}

func (t *RdsInstance) Lcuuid() string {
	return t.lcuuid
}

func (t *RdsInstance) Id() int {
	return t.id
}

func (t *RdsInstance) Name() string {
	return t.name
}

func (t *RdsInstance) RegionId() int {
	return t.regionId
}

func (t *RdsInstance) AzId() int {
	return t.azId
}

func (t *RdsInstance) VpcId() int {
	return t.vpcId
}

func (t *RdsInstance) reset(dbItem *metadbmodel.RDSInstance, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.vpcId = dbItem.VPCID
}

func NewRdsInstanceCollection(t *Tool) *RdsInstanceCollection {
	c := new(RdsInstanceCollection)
	c.collection = newCollectionBuilder[*RdsInstance]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_RDS_INSTANCE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.RDSInstance { return new(metadbmodel.RDSInstance) }).
		withCacheItemFactory(func() *RdsInstance { return new(RdsInstance) }).
		build()
	return c
}

// RdsInstanceCollection defines a collection that maps individual fields to the RdsInstance cache data structure.
type RdsInstanceCollection struct {
	collection[*RdsInstance, *metadbmodel.RDSInstance]
}
