// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// RedisInstance defines cache data structure.
type RedisInstance struct {
	lcuuid   string
	id       int
	name     string
	regionID int
	azID     int
	vpcID    int
}

func (t *RedisInstance) IsValid() bool {
	return t.lcuuid != ""
}

func (t *RedisInstance) Lcuuid() string {
	return t.lcuuid
}

func (t *RedisInstance) ID() int {
	return t.id
}

func (t *RedisInstance) Name() string {
	return t.name
}

func (t *RedisInstance) RegionID() int {
	return t.regionID
}

func (t *RedisInstance) AZID() int {
	return t.azID
}

func (t *RedisInstance) VPCID() int {
	return t.vpcID
}

func (t *RedisInstance) reset(dbItem *metadbmodel.RedisInstance, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionID = tool.Region().GetByLcuuid(dbItem.Region).ID()
	t.azID = tool.AZ().GetByLcuuid(dbItem.AZ).ID()
	t.vpcID = dbItem.VPCID
}

func NewRedisInstanceCollection(t *Tool) *RedisInstanceCollection {
	c := new(RedisInstanceCollection)
	c.collection = newCollectionBuilder[*RedisInstance]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_REDIS_INSTANCE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.RedisInstance { return new(metadbmodel.RedisInstance) }).
		withCacheItemFactory(func() *RedisInstance { return new(RedisInstance) }).
		build()
	return c
}

// RedisInstanceCollection defines a collection that maps individual fields to the RedisInstance cache data structure.
type RedisInstanceCollection struct {
	collection[*RedisInstance, *metadbmodel.RedisInstance]
}
