// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// RedisInstance defines cache data structure.
type RedisInstance struct {
	lcuuid   string
	id       int
	name     string
	regionId int
	azId     int
	vpcId    int
}

func (t *RedisInstance) IsValid() bool {
	return t.lcuuid != ""
}

func (t *RedisInstance) Lcuuid() string {
	return t.lcuuid
}

func (t *RedisInstance) Id() int {
	return t.id
}

func (t *RedisInstance) Name() string {
	return t.name
}

func (t *RedisInstance) RegionId() int {
	return t.regionId
}

func (t *RedisInstance) AzId() int {
	return t.azId
}

func (t *RedisInstance) VpcId() int {
	return t.vpcId
}

func (t *RedisInstance) reset(dbItem *metadbmodel.RedisInstance, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.vpcId = dbItem.VPCID
}

func NewRedisInstanceCollection(t *Tool) *RedisInstanceCollection {
	c := new(RedisInstanceCollection)
	c.collection = newCollectionBuilder[*RedisInstance]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_REDIS_INSTANCE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.RedisInstance { return new(metadbmodel.RedisInstance) }).
		withCacheItemFactory(func() *RedisInstance { return new(RedisInstance) }).
		build()
	return c
}

// RedisInstanceCollection defines a collection that maps individual fields to the RedisInstance cache data structure.
type RedisInstanceCollection struct {
	collection[*RedisInstance, *metadbmodel.RedisInstance]
}
