// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Region defines cache data structure.
type Region struct {
	lcuuid string
	id     int
}

func (t *Region) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Region) Lcuuid() string {
	return t.lcuuid
}

func (t *Region) ID() int {
	return t.id
}

func (t *Region) reset(dbItem *metadbmodel.Region, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
}

func NewRegionCollection(t *Tool) *RegionCollection {
	c := new(RegionCollection)
	c.collection = newCollectionBuilder[*Region]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_REGION_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Region { return new(metadbmodel.Region) }).
		withCacheItemFactory(func() *Region { return new(Region) }).
		build()
	return c
}

// RegionCollection defines a collection that maps individual fields to the Region cache data structure.
type RegionCollection struct {
	collection[*Region, *metadbmodel.Region]
}
