// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Subnet defines cache data structure.
type Subnet struct {
	lcuuid    string
	id        int
	name      string
	networkID int
}

func (t *Subnet) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Subnet) Lcuuid() string {
	return t.lcuuid
}

func (t *Subnet) ID() int {
	return t.id
}

func (t *Subnet) Name() string {
	return t.name
}

func (t *Subnet) NetworkID() int {
	return t.networkID
}

func (t *Subnet) reset(dbItem *metadbmodel.Subnet, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.networkID = dbItem.NetworkID
}

func NewSubnetCollection(t *Tool) *SubnetCollection {
	c := new(SubnetCollection)
	c.collection = newCollectionBuilder[*Subnet]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_SUBNET_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.Subnet { return new(metadbmodel.Subnet) }).
		withCacheItemFactory(func() *Subnet { return new(Subnet) }).
		build()
	return c
}

// SubnetCollection defines a collection that maps individual fields to the Subnet cache data structure.
type SubnetCollection struct {
	collection[*Subnet, *metadbmodel.Subnet]
}
