// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Vinterface defines cache data structure.
type Vinterface struct {
	lcuuid     string
	id         int
	name       string
	ifType     int
	index      int
	mac        string
	regionId   int
	networkId  int
	vpcId      int
	deviceType int
	deviceId   int
	VinterfaceExt
}

func (t *Vinterface) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Vinterface) Lcuuid() string {
	return t.lcuuid
}

func (t *Vinterface) Id() int {
	return t.id
}

func (t *Vinterface) Name() string {
	return t.name
}

func (t *Vinterface) IfType() int {
	return t.ifType
}

func (t *Vinterface) Index() int {
	return t.index
}

func (t *Vinterface) Mac() string {
	return t.mac
}

func (t *Vinterface) RegionId() int {
	return t.regionId
}

func (t *Vinterface) NetworkId() int {
	return t.networkId
}

func (t *Vinterface) VpcId() int {
	return t.vpcId
}

func (t *Vinterface) DeviceType() int {
	return t.deviceType
}

func (t *Vinterface) DeviceId() int {
	return t.deviceId
}

func (t *Vinterface) DeviceName() string {
	return t.deviceName
}

func (t *Vinterface) reset(dbItem *metadbmodel.VInterface, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.ifType = dbItem.Type
	t.index = dbItem.Index
	t.mac = dbItem.Mac
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.networkId = dbItem.NetworkID
	t.vpcId = dbItem.VPCID
	t.deviceType = dbItem.DeviceType
	t.deviceId = dbItem.DeviceID
	t.resetExt(dbItem, tool)
}

func NewVinterfaceCollection(t *Tool) *VinterfaceCollection {
	c := new(VinterfaceCollection)
	c.resetExt()
	c.collection = newCollectionBuilder[*Vinterface]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VINTERFACE_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VInterface { return new(metadbmodel.VInterface) }).
		withCacheItemFactory(func() *Vinterface { return new(Vinterface) }).
		withExtender(c).
		build()
	return c
}

// VinterfaceCollection defines a collection that maps individual fields to the Vinterface cache data structure.
type VinterfaceCollection struct {
	collection[*Vinterface, *metadbmodel.VInterface]
	VinterfaceCollectionExt
}
