// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Vm defines cache data structure.
type Vm struct {
	lcuuid    string
	id        int
	name      string
	regionId  int
	azId      int
	vpcId     int
	hostId    int
	networkId int
	podNodeId int
}

func (t *Vm) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Vm) Lcuuid() string {
	return t.lcuuid
}

func (t *Vm) Id() int {
	return t.id
}

func (t *Vm) Name() string {
	return t.name
}

func (t *Vm) RegionId() int {
	return t.regionId
}

func (t *Vm) AzId() int {
	return t.azId
}

func (t *Vm) VpcId() int {
	return t.vpcId
}

func (t *Vm) HostId() int {
	return t.hostId
}

func (t *Vm) NetworkId() int {
	return t.networkId
}

func (t *Vm) PodNodeId() int {
	return t.podNodeId
}

func (t *Vm) SetPodNodeId(podNodeId int) {
	t.podNodeId = podNodeId
}

func (t *Vm) reset(dbItem *metadbmodel.VM, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.azId = tool.Az().GetByLcuuid(dbItem.AZ).Id()
	t.vpcId = dbItem.VPCID
	t.hostId = dbItem.HostID
	t.networkId = dbItem.NetworkID
}

func NewVmCollection(t *Tool) *VmCollection {
	c := new(VmCollection)
	c.collection = newCollectionBuilder[*Vm]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VM_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VM { return new(metadbmodel.VM) }).
		withCacheItemFactory(func() *Vm { return new(Vm) }).
		build()
	return c
}

// VmCollection defines a collection that maps individual fields to the Vm cache data structure.
type VmCollection struct {
	collection[*Vm, *metadbmodel.VM]
}
