// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// VmPodNodeConnection defines cache data structure.
type VmPodNodeConnection struct {
	lcuuid    string
	id        int
	vmId      int
	podNodeId int
}

func (t *VmPodNodeConnection) IsValid() bool {
	return t.lcuuid != ""
}

func (t *VmPodNodeConnection) Lcuuid() string {
	return t.lcuuid
}

func (t *VmPodNodeConnection) Id() int {
	return t.id
}

func (t *VmPodNodeConnection) VmId() int {
	return t.vmId
}

func (t *VmPodNodeConnection) PodNodeId() int {
	return t.podNodeId
}

func (t *VmPodNodeConnection) reset(dbItem *metadbmodel.VMPodNodeConnection, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.vmId = dbItem.VMID
	t.podNodeId = dbItem.PodNodeID
}

func NewVmPodNodeConnectionCollection(t *Tool) *VmPodNodeConnectionCollection {
	c := new(VmPodNodeConnectionCollection)
	c.collection = newCollectionBuilder[*VmPodNodeConnection]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VM_POD_NODE_CONNECTION_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VMPodNodeConnection { return new(metadbmodel.VMPodNodeConnection) }).
		withCacheItemFactory(func() *VmPodNodeConnection { return new(VmPodNodeConnection) }).
		build()
	return c
}

// VmPodNodeConnectionCollection defines a collection that maps individual fields to the VmPodNodeConnection cache data structure.
type VmPodNodeConnectionCollection struct {
	collection[*VmPodNodeConnection, *metadbmodel.VMPodNodeConnection]
}
