// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Vpc defines cache data structure.
type Vpc struct {
	lcuuid string
	id     int
}

func (t *Vpc) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Vpc) Lcuuid() string {
	return t.lcuuid
}

func (t *Vpc) Id() int {
	return t.id
}

func (t *Vpc) reset(dbItem *metadbmodel.VPC, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
}

func NewVpcCollection(t *Tool) *VpcCollection {
	c := new(VpcCollection)
	c.collection = newCollectionBuilder[*Vpc]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VPC_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VPC { return new(metadbmodel.VPC) }).
		withCacheItemFactory(func() *Vpc { return new(Vpc) }).
		build()
	return c
}

// VpcCollection defines a collection that maps individual fields to the Vpc cache data structure.
type VpcCollection struct {
	collection[*Vpc, *metadbmodel.VPC]
}
