// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// VPC defines cache data structure.
type VPC struct {
	lcuuid string
	id     int
}

func (t *VPC) IsValid() bool {
	return t.lcuuid != ""
}

func (t *VPC) Lcuuid() string {
	return t.lcuuid
}

func (t *VPC) ID() int {
	return t.id
}

func (t *VPC) reset(dbItem *metadbmodel.VPC, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
}

func NewVPCCollection(t *Tool) *VPCCollection {
	c := new(VPCCollection)
	c.collection = newCollectionBuilder[*VPC]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VPC_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VPC { return new(metadbmodel.VPC) }).
		withCacheItemFactory(func() *VPC { return new(VPC) }).
		build()
	return c
}

// VPCCollection defines a collection that maps individual fields to the VPC cache data structure.
type VPCCollection struct {
	collection[*VPC, *metadbmodel.VPC]
}
