// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Vrouter defines cache data structure.
type Vrouter struct {
	lcuuid         string
	id             int
	name           string
	regionId       int
	vpcId          int
	gwLaunchServer string
}

func (t *Vrouter) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Vrouter) Lcuuid() string {
	return t.lcuuid
}

func (t *Vrouter) Id() int {
	return t.id
}

func (t *Vrouter) Name() string {
	return t.name
}

func (t *Vrouter) RegionId() int {
	return t.regionId
}

func (t *Vrouter) VpcId() int {
	return t.vpcId
}

func (t *Vrouter) GwLaunchServer() string {
	return t.gwLaunchServer
}

func (t *Vrouter) reset(dbItem *metadbmodel.VRouter, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.name = dbItem.Name
	t.regionId = tool.Region().GetByLcuuid(dbItem.Region).Id()
	t.vpcId = dbItem.VPCID
	t.gwLaunchServer = dbItem.GWLaunchServer
}

func NewVrouterCollection(t *Tool) *VrouterCollection {
	c := new(VrouterCollection)
	c.collection = newCollectionBuilder[*Vrouter]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VROUTER_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VRouter { return new(metadbmodel.VRouter) }).
		withCacheItemFactory(func() *Vrouter { return new(Vrouter) }).
		build()
	return c
}

// VrouterCollection defines a collection that maps individual fields to the Vrouter cache data structure.
type VrouterCollection struct {
	collection[*Vrouter, *metadbmodel.VRouter]
}
