// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// Vtap defines cache data structure.
type Vtap struct {
	id             int
	lcuuid         string
	name           string
	aType          int
	launchServerId int
}

func (t *Vtap) IsValid() bool {
	return t.lcuuid != ""
}

func (t *Vtap) Id() int {
	return t.id
}

func (t *Vtap) Lcuuid() string {
	return t.lcuuid
}

func (t *Vtap) Name() string {
	return t.name
}

func (t *Vtap) AType() int {
	return t.aType
}

func (t *Vtap) LaunchServerId() int {
	return t.launchServerId
}

func (t *Vtap) reset(dbItem *metadbmodel.VTap, tool *Tool) {
	t.id = dbItem.ID
	t.lcuuid = dbItem.Lcuuid
	t.name = dbItem.Name
	t.aType = dbItem.Type
	t.launchServerId = dbItem.LaunchServerID
}

func NewVtapCollection(t *Tool) *VtapCollection {
	c := new(VtapCollection)
	c.collection = newCollectionBuilder[*Vtap]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VTAP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VTap { return new(metadbmodel.VTap) }).
		withCacheItemFactory(func() *Vtap { return new(Vtap) }).
		build()
	return c
}

// VtapCollection defines a collection that maps individual fields to the Vtap cache data structure.
type VtapCollection struct {
	collection[*Vtap, *metadbmodel.VTap]
}
