// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// VTap defines cache data structure.
type VTap struct {
	id             int
	lcuuid         string
	name           string
	aType          int
	launchServerID int
}

func (t *VTap) IsValid() bool {
	return t.lcuuid != ""
}

func (t *VTap) ID() int {
	return t.id
}

func (t *VTap) Lcuuid() string {
	return t.lcuuid
}

func (t *VTap) Name() string {
	return t.name
}

func (t *VTap) Type() int {
	return t.aType
}

func (t *VTap) LaunchServerID() int {
	return t.launchServerID
}

func (t *VTap) reset(dbItem *metadbmodel.VTap, tool *Tool) {
	t.id = dbItem.ID
	t.lcuuid = dbItem.Lcuuid
	t.name = dbItem.Name
	t.aType = dbItem.Type
	t.launchServerID = dbItem.LaunchServerID
}

func NewVTapCollection(t *Tool) *VTapCollection {
	c := new(VTapCollection)
	c.collection = newCollectionBuilder[*VTap]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_VTAP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.VTap { return new(metadbmodel.VTap) }).
		withCacheItemFactory(func() *VTap { return new(VTap) }).
		build()
	return c
}

// VTapCollection defines a collection that maps individual fields to the VTap cache data structure.
type VTapCollection struct {
	collection[*VTap, *metadbmodel.VTap]
}
