// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// WanIp defines cache data structure.
type WanIp struct {
	lcuuid       string
	id           int
	ip           string
	vinterfaceId int
}

func (t *WanIp) IsValid() bool {
	return t.lcuuid != ""
}

func (t *WanIp) Lcuuid() string {
	return t.lcuuid
}

func (t *WanIp) Id() int {
	return t.id
}

func (t *WanIp) Ip() string {
	return t.ip
}

func (t *WanIp) VinterfaceId() int {
	return t.vinterfaceId
}

func (t *WanIp) reset(dbItem *metadbmodel.WANIP, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.ip = dbItem.IP
	t.vinterfaceId = dbItem.VInterfaceID
}

func NewWanIpCollection(t *Tool) *WanIpCollection {
	c := new(WanIpCollection)
	c.resetExt()
	c.collection = newCollectionBuilder[*WanIp]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_WAN_IP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.WANIP { return new(metadbmodel.WANIP) }).
		withCacheItemFactory(func() *WanIp { return new(WanIp) }).
		withExtender(c).
		build()
	return c
}

// WanIpCollection defines a collection that maps individual fields to the WanIp cache data structure.
type WanIpCollection struct {
	collection[*WanIp, *metadbmodel.WANIP]
	WanIpCollectionExt
}
