// Code generated by generator; DO NOT EDIT.

package tool

import (
	ctrlrcommon "github.com/deepflowio/deepflow/server/controller/common"
	metadbmodel "github.com/deepflowio/deepflow/server/controller/db/metadb/model"
)

// WANIP defines cache data structure.
type WANIP struct {
	lcuuid       string
	id           int
	ip           string
	vInterfaceID int
}

func (t *WANIP) IsValid() bool {
	return t.lcuuid != ""
}

func (t *WANIP) Lcuuid() string {
	return t.lcuuid
}

func (t *WANIP) ID() int {
	return t.id
}

func (t *WANIP) IP() string {
	return t.ip
}

func (t *WANIP) VInterfaceID() int {
	return t.vInterfaceID
}

func (t *WANIP) reset(dbItem *metadbmodel.WANIP, tool *Tool) {
	t.lcuuid = dbItem.Lcuuid
	t.id = dbItem.ID
	t.ip = dbItem.IP
	t.vInterfaceID = dbItem.VInterfaceID
}

func NewWANIPCollection(t *Tool) *WANIPCollection {
	c := new(WANIPCollection)
	c.resetExt()
	c.collection = newCollectionBuilder[*WANIP]().
		withResourceType(ctrlrcommon.RESOURCE_TYPE_WAN_IP_EN).
		withTool(t).
		withDBItemFactory(func() *metadbmodel.WANIP { return new(metadbmodel.WANIP) }).
		withCacheItemFactory(func() *WANIP { return new(WANIP) }).
		withExtender(c).
		build()
	return c
}

// WANIPCollection defines a collection that maps individual fields to the WANIP cache data structure.
type WANIPCollection struct {
	collection[*WANIP, *metadbmodel.WANIP]
	WANIPCollectionExt
}
