on: 
  pull_request:
    paths-ignore:
      - 'agent/**'
      - 'message/**'

name: verify agent

jobs:
  verify_agent:
    name: verify agent
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '