name: build server builder image

on:
  push:
    branches:
      - main
      - 'feature-**'
    paths:
      - 'server/Dockerfile.builder'
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      ref:
        description: "Why trigger?"
        required: true
        type: string

env:
  BUILDER_IMAGE: "deepflow-server-builder"

jobs:
  build_server_builder_image:
    name: build server builder image
    runs-on: "cirun-aws-amd64-32c--${{ github.run_id }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GHCR_PUSH_TOKEN }}"

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: "deepflowce"
          password: "${{ secrets.REGISTRY_PASS }}"

      - name: Log in to ALIYUN HongKong Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "registry.cn-hongkong.aliyuncs.com"
          username: "${{ secrets.REGISTRY_ALIYUN_USER }}"
          password: "${{ secrets.REGISTRY_PASS }}"

      - name: Log in to ALIYUN Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "registry.cn-beijing.aliyuncs.com"
          username: "${{ secrets.REGISTRY_ALIYUN_USER }}"
          password: "${{ secrets.REGISTRY_PASS }}"

      - name: set env
        run: |
          echo "IMAGE_TAG_PREFIX=${{ github.ref_name }}"|sed 's|=main$|=latest|' >> $GITHUB_ENV

      - name: Build and push deepflow server builder images all registries
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: server/Dockerfile.builder
          platforms: linux/amd64,linux/arm64
          tags: |
            "ghcr.io/${{ github.repository_owner }}/deepflow-ce/${{ env.BUILDER_IMAGE }}:${{ env.IMAGE_TAG_PREFIX }}"
            "deepflowce/${{ env.BUILDER_IMAGE }}:${{ env.IMAGE_TAG_PREFIX }}"
            "registry.cn-hongkong.aliyuncs.com/deepflow-ce/${{ env.BUILDER_IMAGE }}:${{ env.IMAGE_TAG_PREFIX }}"
            "registry.cn-beijing.aliyuncs.com/deepflow-ce/${{ env.BUILDER_IMAGE }}:${{ env.IMAGE_TAG_PREFIX }}"
