name: sqlcheck 
on: 
  pull_request:
    paths:
      - 'server/controller/db/metadb/migrator/schema/rawsql/mysql/init.sql'
      - 'server/controller/db/metadb/migrator/schema/rawsql/mysql/issu/*.sql'
jobs:
  sqlcheck:
    name: sqlcheck job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: yokawasa/action-sqlcheck@v1.4.0
      id: sqlcheck
      with:
        post-comment: true
        risk-level: 3
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}
        postfixes: |
          sql
        directories: |
          server/controller/db/metadb/migrator/schema/rawsql/mysql/
          server/controller/db/metadb/migrator/schema/rawsql/mysql/issu/